### ISSUE TITLE
Clarification on dedicated or shared use of switches

### ISSUE THREAD

**Issue by adyjoy** [NetAppDocs/ontap-metrocluster#100]
Page: [Considerations for using MetroCluster-compliant switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html)
Please clarify if the replacement MetroCluster-compliant switches must be dedicated to the MetroCluster, or can be used to providing shared network services to non-MetroCluster compute nodes (for example).

**Comment by netapp-folivia** [comment]
Hello, thank you for your feedback. We have reviewed this section and made a few changes. You'll see this reflected in our pages very soon.
