### ISSUE TITLE
ONTAP Mediator and SCT

### ISSUE THREAD

**Issue by ArnaudAlbertini** [NetAppDocs/ontap-metrocluster#102]
Page: [Preparing to install the ONTAP Mediator service](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html)

Hello Team,

It is quite difficult to the follow the dependencies between the 2 pages "Preparing to install the ONTAP Mediator service" "Installing or upgrading the ONTAP Mediator service".

In the first page we talk about the versions :
ONTAP Mediator 1.0 requires scst-3.3.0.tar.bz2
ONTAP Mediator 1.1 requires scst-3.4.0.tar.bz2

But in the second page we can see the only supported ONTAP Mediator versions are 1.2 - 1.3

Do we have a better way to view the supported components and OS versions etc ?

**Comment by netapp-folivia** [comment]
Hi Arnaud, Marty confirmed that we can improve this documentation and remove 1.0 and 1.1. You'll see the updates very soon. Thanks!

**Comment by netapp-folivia** [comment]
@thrisun, Marty suggested I reassign this issue to you as you're working on this topic. Thanks!
