### ISSUE TITLE
Clarification required on transition information page

### ISSUE THREAD

**Issue by pgbachman** [NetAppDocs/ontap-metrocluster#103]
Page: [Supported platforms for nondisruptive transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_supported_platforms_for_transition.html)

The Information item on this page needs clarification, as there is confusion in the field as to what is a "shared switch configuration"

![Transition_info](https://user-images.githubusercontent.com/3339516/139873128-0e7aee18-0944-45d4-b9bf-738172f6ea7d.jpg)

Please amend this information item along these lines. 

"Transitioning to a Cisco 9336C-FX2 **_shared switch_** configuration is not supported. 

A **_shared switch_** configuration is one where the switches provide BOTH the MetroCluster connections and the storage disk shelf connections. Configurations where the Cisco 9336C-FX2 provides only the MetroCluster connections are supported."

**Comment by netapp-martyh** [comment]
Resolved in hotfix 2021.11.21.
