### ISSUE TITLE
Configuring and connecting the MetroCluster IP interfaces - Step 5. Create the interfaces on "node_B_1".

### ISSUE THREAD

**Issue by masoodolip** [NetAppDocs/ontap-metrocluster#105]
Page: [Configuring the clusters into a MetroCluster configuration](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html)

Create the interfaces on "node_B_1".

5. a & b commands need to be modified as the interfaces are getting created on Cluster B. but the command says Cluster_A

5a. cluster_A::> metrocluster configuration-settings interface create -cluster-name cluster_A -home-node node_B_1 -home-port e5a -address 10.1.1.3 -netmask 255.255.255.0
[Job 28] Job succeeded: Interface Create is successful.cluster_A::>

5b. cluster_A::> metrocluster configuration-settings interface create -cluster-name cluster_A -home-node node_B_1 -home-port e5b -address 10.1.2.3 -netmask 255.255.255.0
[Job 28] Job succeeded: Interface Create is successful.cluster_A::>

**Comment by netapp-martyh** [comment]
Fixed in hotfix 2021.11.21.
