### ISSUE TITLE
Automatic partitioning option unclear

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#107]
Page: [Considerations for automatic drive assignment and ADP systems in ONTAP 9.4 and later](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_drive_assignment.html)

Can we confirm and update - if necessary - in the "Automatic Partitioning" section what is "disk auto=assignment"? Does that refer to setting up the following option: 

::> run -node NodeA -command options disk.auto_assign on

Thanks!

**Comment by netapp-martyh** [comment]
Thanks, Viktor, for the feedback. We will investigate and update the doc to clarify.

**Comment by netapp-folivia** [comment]
Hi Viktor, I've resolved this issue. You'll see the new, correct command on our pages in the next couple of days. Thanks!
