### ISSUE TITLE
Cisco 9336C-FX2 switch is missing from the table

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#108]
Page: [Considerations for ISLs](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_isls.html)

Cisco 9336C-FX2 switch is missing from the table

**Comment by netapp-aoife** [comment]
Hi, this issue has now been addressed in the documentation. Thanks again for bringing this up. You can view the updates here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_isls.html#number-of-isls-and-breakout-cables-in-the-shared-network
