### ISSUE TITLE
Cluster peering introduction info is repeated 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#109]
Page: [Cluster peering](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_peering.html)

The opening 2 sentences are repeated twice in the opening, which doesn't really makes sense.

**Comment by netapp-martyh** [comment]
Thanks, Viktor. This will be fixes in the next update of the docs probably within the next week or two.

**Comment by netapp-folivia** [comment]
Hi, thanks for noticing this error. I've updated the documentation and  you'll be able to see this update in the next couple of days.
