### ISSUE TITLE
Add BES firmware upgrade info for 3.8.0.2

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#112]
Page: [Configuring Broadcom IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html)

In the "Downloading and installing the Broadcom switch EFOS software" section we don't have info for 3.8.0.2, which should be pretty similar to 3.7.0.4 (in terms of upgrade from older releases)

**Comment by netapp-folivia** [comment]
Hi Viktor, Thanks for your feedback. I'll update the documentation as needed.

**Comment by netapp-folivia** [comment]
Hi! I've clarified this section. You can view the updates here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software
