### ISSUE TITLE
MetroCluster IP plexes state after power on 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#113]
Page: [Powering off and powering on a data center](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_on_and_power_off_a_data_center.html)

I received a question about "Powering on the MetroCluster configuration and returning to normal operation" and MCC-IP configurations - is customer supposed to online the plexes at that point in Step 5 - similar to what we have for the FC configurations?

I don't really think ONTAP will automatically power on plexes in a MCC-IP scenario, but can we double check that and update the KB with that step as well, if necessary. 

Thanks!

**Comment by netapp-folivia** [comment]
Thank you. We'll take a look and update the documentation if required.

**Comment by netapp-folivia** [comment]
Hi Viktor, I've clarified the documentation to say that these plexes remain online. You'll the updates reflected on our pages soon. Thanks!
