### ISSUE TITLE
Document mistakes/improvements

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#115]
Page: [Cluster peering](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_peering.html)

The statement at the top of the page is repeated twice:

"Each MetroCluster site is configured as a peer to its partner site. You should be familiar with the prerequisites and guidelines for configuring the peering relationships and when deciding whether to use shared or dedicated ports for those relationships. Each MetroCluster site is configured as a peer to its partner site. You must be familiar with the prerequisites and guidelines for configuring the peering relationships. This is important when deciding on whether to use shared or dedicated ports for those relationships."

Also:

"The subnet must have enough IP addresses available to allocate to one intercluster LIF per node.

For example, in a six-node cluster, the subnet used for intercluster communication must have six available IP addresses."

There is no such thing as a six-node MetroCluster so it might make more sense to put four-node MetroCluster instead:

"The subnet must have enough IP addresses available to allocate to one intercluster LIF per node.

For example, in a four-node MetroCluster, the subnet used for intercluster communication must have four available IP addresses."

**Comment by netapp-folivia** [comment]
Hi, I'm aware if the first issue and I'll take a look at the second. Thanks for letting us know!

**Comment by netapp-folivia** [comment]
Hi, we have updated the documentation and you'll see the changes reflected soon. Thanks!
