### ISSUE TITLE
TieBreaker 1.3 is not yet available for download 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#116]
Page: [Installing the Tiebreaker software](https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/task_install_the_tiebreaker_software.html)

Latest available version is 1.21P3 as per https://mysupport.netapp.com/site/products/all/details/metrocluster-tiebreaker/downloads-tab

**Comment by netapp-folivia** [comment]
Thanks, Viktor. I'll make this update and you'll the changes reflected in our pages soon.
