### ISSUE TITLE
Firewall Requirements for Cluster Management LIF's and Node Management LIFs

### ISSUE THREAD

**Issue by rijmenantspj** [NetAppDocs/ontap-metrocluster#117]
Page [Firewall requirements for MetroCluster Tiebreaker](https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/reference_firewall_requirements_for_mcc_tiebreaker.html), in my opinion, doesn't distinguish (clear enough) between the firewall requirements for Cluster Management LIF's and Node Management LIFs.

**Comment by netapp-folivia** [comment]
Thank you. We'll take a look at this and update the documents as necessary.

**Comment by rijmenantspj** [comment]
> Thank you. We'll take a look at this and update the documents as necessary.

Thank you for the swift response. Please note I've raised Pull Request #118 on the same.

**Comment by netapp-folivia** [comment]
We've reviewed the table and are currently making updates. You'll see the changes reflected on our pages soon. Thanks!
