### ISSUE TITLE
Formatting in all metrocluster configuration-settings add commands 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#119]
Page: [Preparing to install the ONTAP Mediator service](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html)

The formatting in all metrocluster configuration-settings add is a bit off, showing something like "-addressmediator-ip-address" which could be a bit confusing.

The syntax should be as follows as per http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-970/metrocluster__configuration-settings__mediator__add.html : 

metrocluster configuration-settings mediator add -mediator-address

**Comment by netapp-folivia** [comment]
Thanks Viktor. We'll take a look at this and make the necessary updates.

**Comment by netapp-folivia** [comment]
Hi, we've made the change and you'll see the update on our pages soon. Thanks.
