### ISSUE TITLE
Wrong MetroCluster IP Ports on FAS8300/FAS8700

### ISSUE THREAD

**Issue by aleex42** [NetAppDocs/ontap-metrocluster#123]
Page: [Configuring the clusters into a MetroCluster configuration](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html)

MetroCluster IP port on FAS8300 and FAS8700: e1a / e1b instead of e0c/e0d (these are CLuster Ports)

![2021-12-29 14_17_58-Configuring the clusters into a MetroCluster configuration](https://user-images.githubusercontent.com/5489107/147666413-d523876d-e54b-4420-bb09-cf4aea7d0dc1.png)

**Comment by netapp-folivia** [comment]
Hi, thanks for bringing this to our attention. We'll take a look and make the necessary changes.

**Comment by netapp-folivia** [comment]
We've updated the documentation and you'll see this reflected in our pages very soon. Thanks!
