### ISSUE TITLE
Upgrdaing from 3.4.x.x to 3.7.x + 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#126]
Page: [Configuring Broadcom IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html)

Hello everyone, 

Just noticed that there might be an issue when upgrading from 3.4.4.6 to 3.7.0.4+ as those releases use different RCF files, in terms of the Cluster communication between the local nodes and the DR/AUX ISCSI sessions/NVRAM replication. 

This might have to be checked further, but a customer tried upgrading one of their switches to 3.7.0.4 and applying the correct RCF file as per the latest RCF generator - that resulted in out of quorum state due to Cluster VLAN being different (not the same as Native VLAN 1 used before), which led to one switch tagging cluster traffic with VLAN 1 and the other with VLAN 103. 

After doing some additional tests, one cluster ended up with both switches running 3.4.4.6 and the other - 3.7.0.4. Cluster communication was okay, but remote DR/AUX sessions were down, although the port configuration and VLANs looks the same. Reverting on the the switches to 3.4.4.6 and re-applying the old RCF recovered the sessions. 

Eventually the issue was resolved by manually moving cluster LIFs from the switch, which is to be upgraded to the other in the local HA pair, then moving them to the recently upgraded one, upgrading it and so on. 

However, there a few things, which might cause a problem here for other customers: 

1. During switch upgrade we might go OOQ due to Cluster VLAN mismatch and cluster traffic being disrupted. 
2. Possibly there might be remote communication issues due to the different RCF files applied on switches in the same fabric. 

So the whole procedure doesn't seem to be very straight forward for some scenarios and it might be a good idea to add some additional steps for such scenarios, just to avoid any issues. 

Thanks!

**Comment by netapp-folivia** [comment]
Thanks, Viktor. We'll take a look at this and update the docs accordingly.

**Comment by netapp-folivia** [comment]
Thanks for the feedback, Viktor. I will track these changes and speak with Engineering regarding necessary updates. Thanks!

**Comment by netapp-folivia** [comment]
Hi, we have revised to documentation so that any potential issues during switch software upgrades are avoided. Thanks!

**Comment by viktorpenev** [comment]
Hello Olivia,

Thank you  for your message.

Can you please let me know if any changes have been made to the documentation?

Best regards,

Viktor Penev
Technical Support Engineer
Technical Support Center

NetApp
***@***.******@***.***>

[A close up of a logo  Description automatically generated]<https://www.netapp.com/us/index.aspx>


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>
