### ISSUE TITLE
wrong ports for A400

### ISSUE THREAD

**Issue by netappmf** [NetAppDocs/ontap-metrocluster#127]
Page: [Verifying the ha-config state of components](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_verify_haconfig.html)

Hi all
the documentation says that the A400 uses Ports e3a/e3b as Metrocluster IP ports. However based on the HWU those are the Cluster Ports and the Metro is using e1a/e1b

![image](https://user-images.githubusercontent.com/97685518/149355416-6222db79-f89d-4397-81c7-f080950c9345.png)

**Comment by netapp-martyh** [comment]
Thanks for providing the feedback. This is a known issue and will be resolved shortly.
