### ISSUE TITLE
Clarify Firewall ports for cluster and node management

### ISSUE THREAD

**Issue by tomdewit** [NetAppDocs/ontap-metrocluster#129]
Page: [Firewall requirements for MetroCluster Tiebreaker](https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/reference_firewall_requirements_for_mcc_tiebreaker.html)
![Screenshot 2022-01-18 at 13 46 38](https://user-images.githubusercontent.com/16240774/149940015-13e1c945-ac40-41fb-b3a7-906c39955fd8.png)

On the firewall ports list, we see two times the same listing for ports 22 and 443 for the Metrocluster management LIF's. I think this must be the 'Metrocluster Node Management LIF's' once and 'Metrocluster Cluster Management LIF's' for the second listing. Can this be changed to provide clarity ? When you read this now, you think that access to the cluster management LIF's is enough, which is not.

**Comment by netapp-folivia** [comment]
Thank you -- we'll take a look and update the table.

**Comment by netapp-aoife** [comment]
Just letting you know that this update has been made, you can view the changes here: https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/reference_firewall_requirements_for_mcc_tiebreaker.html 

Thanks again for bringing this to our attention.
