### ISSUE TITLE
Clarify access rights for the NetApp cluster user

### ISSUE THREAD

**Issue by tomdewit** [NetAppDocs/ontap-metrocluster#130]
Page: [Configuring the Tiebreaker software](https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/concept_configuring_the_tiebreaker_software.html)

If you use another NetApp user than admin, information could be added to which protocol access needs to be enabled for that user on NetApp. In this case it should be ONTAPI and SSH (security login create -application <>)

It should be best practice to create a separate user instead of using the default admin user.

**Comment by netapp-folivia** [comment]
Hi, we'll take a look and update the documentation as needed. Thanks!

**Comment by netapp-folivia** [comment]
This section is currently being revised and will be published soon.

Thanks,
Olivia

**Comment by netapp-folivia** [comment]
Hi Chanda, not yet. This has been delayed as it's tied in with another update.
It should be published later this month,

Thanks.
Olivia

**Comment by netapp-aoife** [comment]
Hi Chanda, this issue is still in progress. Please leave it open. Thanks!

**Comment by netapp-aoife** [comment]
Hi there, thank you again for raising this in the documentation. The issue is addressed here: https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/task_configure_ssh_ontapi.html
