### ISSUE TITLE
404 for transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html

### ISSUE THREAD

**Issue by netapp-thomi** [NetAppDocs/ontap-metrocluster#131]
[Page: [MetroCluster Documentation](https://docs.netapp.com/us-en/ontap-metrocluster/index.html)](https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html)  gives a 404 error

**Comment by netapp-folivia** [comment]
Thank you, Thom! This page is visible once more, but I appreciate you letting me know!
