### ISSUE TITLE
Reword on first two sentences to clarify that task MUST be repeated on each switch in succession.

### ISSUE THREAD

**Issue by Druplu** [NetAppDocs/ontap-metrocluster#132]
Page: [Upgrading firmware on MetroCluster IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_firmware_on_mcc_ip_switches.html)

A high level overview process needs to be included. At very least the top 2 sentences should be clarified.  

When you install the switch software on each of the switch, you must first check the health of the configuration. < this may make the customer think they should use mcc check
You must repeat this task on each of the switch in succession to ensure that all MetroCluster components are healthy. < this is the truth, the task must be repeated on each switch in succession. 

I hope that's clear. Please reach out if it's not drew.plumm@netapp.com

**Comment by netapp-folivia** [comment]
Hi, thanks for your feedback. We'll take a look and update the documentation accordingly.

**Comment by netapp-folivia** [comment]
We've updated this section to improve clarity. You can see the updates here: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_firmware_on_mcc_ip_switches.html Thanks!
