### ISSUE TITLE
Add warning for using intermediate switches 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#135]
Page: [Configuring Broadcom IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html)

Can we add a warning that if you use intermediate switches it is highly recommended to review the new RCF files ISL config (when upgrading) and make sure that the intermediate switches will be able to communicate with the BES switches after the new files are applied?

For example: 

"If they go to intermediate switches, and the MCC ISL changes from access to trunk – then yes, it would remain down until they reconfigure the switchport / trunk on the intermediate switches into trunk mode as well."

**Comment by netapp-martyh** [comment]
Thanks, Viktor. We will review your suggestion with the team and make updates as needed. Have a good weekend.
