### ISSUE TITLE
Add clarification on HA capabilities / failover functionality

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#138]
Page: [Setting up ONTAP](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_setup_ontap.html)

Hello everyone, 

Can we add a clarification on HA capabilities / failover functionality during MetroCluster IP installations as we're seeing cases, where customer expect that to work after the cluster setup, which is not the case, e.g. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/HA_Interconnect_down_during_MetroCluster_IP_installation

We're also seeing issues where the T6 ports do not come up before the creating of the MetroCluster IP interfaces, which can also cause some confusion as people think something is wrong with their hardware setup. 

Thanks!

**Comment by netapp-folivia** [comment]
Thanks, Viktor! We'll take a look and revise this section.

**Comment by viktorpenev** [comment]
One more thing might worth adding - another customer is at this step - https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html#creating-the-dr-group Creating the DR group

However, they've noticed the following errors: 

Reason Takeover not Possible: Storage failover interconnect error
                     NVRAM log not synchronized
                     Disk inventory not exchanged
                     
While this might be expected at this step of the installation process, we might be able to avoid creation of such cases if we simply state that prior to creating the MetroCluster IP interfaces that's not supposed to work.

**Comment by netapp-folivia** [comment]
Thanks, Viktor. That sounds like a good idea. I'll find out more and let you know.

**Comment by netapp-folivia** [comment]
Thank you. This section is currently in review and should be updated soon.

Thanks,
Olivia

**Comment by netapp-folivia** [comment]
Hi Viktor,

We've added some more details about what is enabled before running 'metrocluster configure': [Configuring the clusters into a MetroCluster configuration](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html)

Thanks!
Olivia
