### ISSUE TITLE
Centos-Vault.repo entry has return character in the wrong place

### ISSUE THREAD

**Issue by MarktheSpark17** [NetAppDocs/ontap-metrocluster#139]
Page: [Installing or upgrading the ONTAP Mediator service](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_configure_mediator.html)

Currently the entry is as follows:

[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$
basearch/gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1

but it should be

[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1

**Comment by netapp-aoife** [comment]
We will look into this. Thanks for bringing it to our attention.

**Comment by netapp-aoife** [comment]
Hi, we updated our documentation to address this issue. You can view the update here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_configure_mediator.html#centos7x

Thanks again for getting in touch.
