### ISSUE TITLE
Change the cluster name in the outputs

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#144]
Page: [Powering off and powering on a data center](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_on_and_power_off_a_data_center.html)

Can you please change the cluster name in the example outputs to match the surviving site from the description? E.g., 

We state that "Cluster_A will be powered off for maintenance." Later we show output from Cluster A, which should actually be down at that point. 

Looking at Step 6, the output itself is correct (coming from Cluster B), just the name of the cluster is not correct. 

Not a big deal, but got a ticket to ask for clarification, cause it wasn't clear to them.

**Comment by netapp-folivia** [comment]
This issue is now resolved (link below). Thanks for your feedback, Viktor. 
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_on_and_power_off_a_data_center.html#powering-off-a-metrocluster-site
