### ISSUE TITLE
When will this document be updated to mediator 1.3 ?

### ISSUE THREAD

**Issue by MikeNETAPP** [NetAppDocs/ontap-metrocluster#149]
Page: [Preparing to install the ONTAP Mediator service](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html)

**Comment by netapp-folivia** [comment]
Hi Mike,  
We don't always update example system outputs with the latest software version, but we'll take a look to see if any improvements can be made. ONTAP Mediator 1.3 is documented as being supported on the next page: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_configure_mediator.html

Thanks!
