### ISSUE TITLE
Suggesting some neccesary changes in the doc

### ISSUE THREAD

**Issue by DDOMohit** [NetAppDocs/ontap-metrocluster#151]
Page: [Renaming a Cisco IP switch](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_rename_a_cisco_ip_switch.html)

**Comment by netapp-folivia** [comment]
Hi, 
Did you wish to leave a comment regarding improvements?
Thanks!

**Comment by netapp-folivia** [comment]
Closing this issue as no feedback was submitted.
