### ISSUE TITLE
Add info on verifying if EFOS image uses FIPS 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#152]
Page: [Configuring Broadcom IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html)

Hello everyone, 

In "Downloading and installing the Broadcom switch EFOS software" we explain how to upgrade the switches depending on whether FIPS/non-FIPS EFOS is used, but we don't tell people how to verify that, in case they don't really know. 

One way that works is (taken from Broadcom EFOS install guide): 

"FIPS build can be identified on a running system using the “show platform vpd” CLI command.

#show platform vpd 

Operational Code Image File Name............... FastPath-EFOS-esw-qcp_td3-qcp_td3_x86_64-LX415R-CNTRF-BD6IOQH_**FIPS**rQv11m30b1"

If there's FIPS in the filename then it uses FIPS.

**Comment by netapp-folivia** [comment]
Hi Viktor, we'll take a look and come back to you soon. Thanks for the feedback!
