### ISSUE TITLE
Remove suggestion for setting MP speed to 'auto' for ATTO bridges 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#154]
Page: [Configuring the FC-to-SAS bridges (MetroCluster FC configurations only)](https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/task_cfg_bridges_mcfc.html)

In step "4. Set the speed on the Ethernet ports by using the set EthernetSpeed port speed command." at the moment it suggests that the speed can be set to "speed can be "100", "1000", or "auto"." 

As we've had a lot of issues with ATTO MP ports set to 'auto' as opposed to using a fixed speed - e.g., https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/ATTO_FibreBridge_is_not_reachable_through_the_management_port_-_out_of_band_management - can you please remove that and specify that has to be set to a fixed speed. 

Thanks!

**Comment by netapp-folivia** [comment]
Thanks, Viktor. I'll verify this update and make the change.

**Comment by viktorpenev** [comment]
Hi Olivia,

I think this was another doc page I had in mind when submitting this feedback - https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/task_configure_the_fc_to_sas_bridges_fb_new_install_configure.html

There we specify the MP speed should be manually set to 1000:

set ethernetspeed mp1 1000

Best regards,

Viktor Penev
Technical Support Engineer
Technical Support Center

NetApp
***@***.******@***.***>

[A close up of a logo  Description automatically generated]<https://www.netapp.com/us/index.aspx>


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

**Comment by netapp-folivia** [comment]
Hi Viktor, thanks for pointing out this issue. I've removed the 'auto' option and this will be published in the next few days.
