### ISSUE TITLE
Edit formatting and clarify on power on procedure 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#155]
Page: [Powering off an entire MetroCluster FC configuration](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_off_an_entire_mcc_fc_configuration.html)

Hello everyone, 

Can you please update the formatting a bit just to make the steps for powering down a bit easier to read (mainly for 4n configurations)? 

At step 6, if we just power on the controllers that won't give us much as drives/shelves/ATTO/switches will be still down (so we probably get stuck at LOADER in the best case scenario). Can we add more steps on properly powering on all the equipment? 

What would be the reason for not having vservers in up state as per the last step? 

Thanks!

**Comment by netapp-folivia** [comment]
Hi Viktor,
We're currently reviewing this procedure and will take all of your comments into consideration.
Thanks!

**Comment by netapp-folivia** [comment]
Hi Viktor, we've made your suggested updates -- thank you for your feedback! See the updates here: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_off_an_entire_mcc_fc_configuration.html
