### ISSUE TITLE
Procedure needs review

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#156]
Page: [Testing the MetroCluster configuration](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_test_the_mcc_configuration.html)

Hi,
Section "Verifying healing and manual switchback" includes an unnecessary step for MCIP- "5. Boot nodes from the disaster site".

This looks to be a carry-over (copy/paste) from the procedure for testing a Fabric MetroCluster. For MC IP the nodes will already have booted (or have never been down) otherwise the aggregate mirrors couldn't have resynced in the previous steps.

Please have someone review this procedure.

Thanks and regards,
Niels

**Comment by netapp-folivia** [comment]
Thank you, Niels! We'll take a look and update the docs accordingly.

**Comment by netapp-folivia** [comment]
Hi Niels,

I've removed this step and you'll see the the update soon.

Thanks,
Olivia
