### ISSUE TITLE
Configuring SNMPv3 in a MetroCluster configuration - Not required

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#160]
Page: [Configuring the MetroCluster software in ONTAP](https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_configuring_the_mcc_software_in_ontap.html)

As this page is part of the Stretch MetroCluster configuration guide, it does not need a section on how to monitor the switches using SNMP as there aren't any switches in this configuration. This section only applies to switch attached configurations.

**Comment by michelef-netapp** [comment]
Specific section is:
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_configuring_the_mcc_software_in_ontap.html#configuring-snmpv3-in-a-metrocluster-configuration

**Comment by netapp-folivia** [comment]
Thanks for the feedback, Michele! I'll make the update.

**Comment by netapp-folivia** [comment]
This section has now been removed. Thanks for letting us know!
