### ISSUE TITLE
Incorrect firmware file type specified in update ATTO update command

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#163]
Page: [Updating firmware on a FibreBridge bridge](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html)

In "Step 6: Update the bridge firmware" the file format listed is .sfp ATTO firmware files are in .zbd format as per https://mysupport.netapp.com/site/products/all/details/atto-fibrebridge/downloads-tab/download/63403/7600N_4.30/downloads

We got a ticket raised to clarify why there's a difference between command in the doc page and firmware available for download.

**Comment by netapp-folivia** [comment]
Thanks, Viktor. I'll correct this error.

**Comment by netapp-folivia** [comment]
This issue is now resolved: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html#updating-firmware-on-fibrebridge-7600n-or-7500n-bridges-on-configurations-running-ontap-9-4-and-later
