### ISSUE TITLE
Section on using Compliant switches ("OpenNetwork") should include tagged VLAN info for A400 etc.

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/ontap-metrocluster#164]
Page: [Considerations for using MetroCluster-compliant switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html)

This page should add the information that for certain platforms, like A400 and FAS8300, the Node ports need to be configured as trunk ports, with the same VLAN ID that will be used during the "metrocluster configuration-settings interface create" command.

Using an Access port on these platforms will not work since they cannot be configured without VLAN for their MCC IP iSCSI interfaces

**Comment by netapp-folivia** [comment]
Hi Michael. Thank you for raising this issue. I'll contact engineering and make the necessary changes.

**Comment by netapp-folivia** [comment]
Hi Michael,

We added a new row to the table, 'Platform-specific network speeds and switch port modes for MetroCluster-compliant switches' showing the switch port modes for the different platforms: 
[Considerations for using MetroCluster-compliant switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html#platform-specific-network-speeds-and-switch-port-modes-for-metrocluster-compliant-switches)

I hope this is helpful and thanks again for your feedback!

Olivia
