### ISSUE TITLE
Statement regarding RCF modification

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#165]
Page: [Configuring Cisco IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_cisco.html)

I think we need to state in the 'Downloading and installing the Cisco IP RCF files' section that we do not support any modifications to the RCFs once generated.

If a change is required, the customer would need to work with their account team to submit an fPVR for the change.

**Comment by netapp-folivia** [comment]
Thank you for helping us create clear documentation. I will add a note to that effect.

**Comment by netapp-folivia** [comment]
A new note has been added to this section: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files
