### ISSUE TITLE
Wrong Site for shutdown in Picture

### ISSUE THREAD

**Issue by Rorari** [NetAppDocs/ontap-metrocluster#168]
Page: [Powering off and powering on a data center](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_on_and_power_off_a_data_center.html)

**Comment by Rorari** [comment]
Wrong location specified at the beginning of the document. In the picture site A is switched off, but the procedure refers to the switching off of site B

**Comment by netapp-folivia** [comment]
Thanks for your comment. This topic is currently being reviewed but I will make this quick update.
