### ISSUE TITLE
Step 3. Mediator link broken

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#169]
Page: [Remove ONTAP Mediator or Tiebreaker monitoring before performing maintenance tasks](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_remove_mediator_or_tiebreaker_when_performing_maintenance_tasks.html)

Step 3 table, mediator link is broken. I assume we want to link to:
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html

**Comment by netapp-folivia** [comment]
Hi Michelle, I checked and the link in step 2 seems to go to an incomplete page -- is that the one you meant? I will fix this. The other link in step 3 seems to be working fine. Thanks!

**Comment by netapp-folivia** [comment]
Yes, I see the issue -- thanks, Michelle! I'll publish this update very soon.
