### ISSUE TITLE
Step 1C line change 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#174]
Page: [Configuring Cisco IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_cisco.html)

Hello everyone, 

In Step 1C there's a line stating "SSH service (RSA) After completing the configuration wizard, the switch reboots." That might have to be separated on a new line, just to avoid any confusion. It's obviously refers to configuring SSH and THEN the switch will reboot as the wizard is complete, but still...

**Comment by netapp-folivia** [comment]
Thanks, Viktor! I've made the update. The documentation will be refreshed in the next day or two.
