### ISSUE TITLE
The procedure listed here is not correct

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#177]
Page: [Manually assigning drives to pool 0](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_assign_pool0.html)

Step 8 states the following:

"Repeat these steps on the other nodes in the MetroCluster IP configuration."

But this is not correct. If you repeat these steps, you will wipe the partner node which you have already initialized.

Instead, 9a needs to be run on both nodes in the HA pair, and then 9b or option 4 can be run to configure the nodes after they have been initialized.

This mistake has caused great confusion for one of our customers recently.

**Comment by netapp-thomi** [comment]
Hi,
Thank you for alerting us about the concern with this procedure step.  We'll have the procedure reviewed again and make corrections accordingly.   
Thanks for helping us keep ONTAP MetroCluster documentations complete and accurate.
Thom

Thom Illingworth
Information Engineering, NetApp

**Comment by netapp-folivia** [comment]
Hi Tom,

Thanks for getting in touch. I've spoken to Engineering and they have reviewed this procedure. They believe the steps are accurate, and that the partner node is wiped during installation. 
I will email you directly and put you in touch with an engineer if you have any further questions.

Thanks!
Olivia
