### ISSUE TITLE
Multiple sections present twice in navigation [was: FAS8300/3700 MC IP port incorrect]

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#178]
Page: [Verifying the ha-config state of components](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_verify_haconfig.html)

Under section "Configuring and connecting the MetroCluster IP interfaces" there is a table listing "The physical ports used by the MetroCluster IP interfaces depends on the platform model"
This table lists wrong ports for platforms FAS8300/8700. Those need to be e1a and e1b.

The very same table exists in a different section later in the documentation:
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html#configuring-and-connecting-the-metrocluster-ip-interfaces
There the table is correct.

While writing this I noticed that not only this table but the whole sections following this table are present twice at the two above mentioned locations.
When interpreting the Installation guide as a sequential series of tasks it does not make sense that these tasks appear twice.
It looks as if the section "setting up ONTAP" and the paragraphs belonging to it are present twice - first time as a sub-section of "Verifying the ha-config state of components" in the right navigation and a second time in the main navigation on the left side as its own section.
For me it looks as if "setting up ONTAP" should not be part of "Verifying the ha-config state of components". That section should end right before "Manually assigning drives to pool 0" as that is yet another section on its own now in the left navigation.

I started this ticket with a wrong table but now it looks as if the whole navigation of several sections is screwed up and appears twice - once in the left navigation as main section and once in the right navigation as sub-sections of "Verifying the ha-config state of components".

Kind regards, Niels

**Comment by netapp-folivia** [comment]
These issues are now resolved: [Verifying the ha-config state of components](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_verify_haconfig.html)
Thank you for bringing it to our attention.
