### ISSUE TITLE
Can we save the old switch config and apply that to the new replacement switch if same model

### ISSUE THREAD

**Issue by Brandon12345678901** [NetAppDocs/ontap-metrocluster#179]
Page: [Replacing a Brocade FC switch](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_brocade_fc_switch_mcc.html)

I wondered can we also mention if the old switch is running we can save the config and apply it to the new switch 
(ref: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FlexPod_with_Infrastructure_Automation/How_to_perform_a_Brocade_switch_replacement_and_renew_or_replace_the_Brocade_license ) 

- or is it best practice just to create the config from scratch each time ?

**Comment by netapp-folivia** [comment]
Hi Brandon,
Thanks for your question. I'll find out the answer and update the documentation if required.

**Comment by netapp-folivia** [comment]
Hi Brandon,

I spoke to Engineering and they think it's best for you to contact technical support for supervision and further information.
[Technical Support](https://www.netapp.com/company/contact-us/support/#technical_support)

Thanks,
Olivia

**Comment by Brandon12345678901** [comment]
Hi Olivia,

Thanks, I'm from Technical Support and what I am asking is that we give details on how o replace a switch but we effectively tell people to configure it from scratch, which takes a long time.

What I was thinking ....Can we also mention in the doc that it is possible to save the configuration of the old switch and then download it onto the replacement one ? This can save some time in replacements .

Thanks,

Brandon Stockil
Senior Technical Support Engineer (SAN)

NetApp
+31 20 703 6881 Direct Phone
+31 20 703 6735 Office Phone<https://www.netapp.com/us/contact-us/support.aspx>
***@***.******@***.***>
