### ISSUE TITLE
Power Panic

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#181]
Page: [Understanding MetroCluster data protection and disaster recovery](https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html)

Under the section "Automatic unplanned switchover in MetroCluster FC configurations", the 3rd point in the bullet list is "Power panic" this should just be "Panic"

**Comment by netapp-folivia** [comment]
Thanks for letting us know, Michelle. I'll make this update.

**Comment by netapp-folivia** [comment]
Hi, this issue is now resolved (see link below). Thanks!
https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#considerations-when-using-unmirrored-aggregates
