### ISSUE TITLE
Customer noticed that it is not needed to perform the task on both clusters

### ISSUE THREAD

**Issue by chmutnik** [NetAppDocs/ontap-metrocluster#183]
Page: [Unconfigure the ONTAP Mediator service from the MetroCluster IP configuration](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_remove_unconfigure_mediator.html)

Customer provided attached Putty log.

Please review if the doc needs to be modified
[mediator_aktivierung_auf_cluster.txt](https://github.com/NetAppDocs/ontap-metrocluster/files/9061452/mediator_aktivierung_auf_cluster.txt)

**Comment by netapp-folivia** [comment]
Hi, 

Thank you for the feedback and for the Putty log.
We'll take a look and make the necessary changes.

Thanks!
Olivia

**Comment by ntap-bmegan** [comment]
@netapp-folivia or @netapp-aoife - Is this work complete? If not, can you provide an estimate?

**Comment by chmutnik** [comment]
Hello team,

I opened this on behalf of the customer.
Technically I can’t judge, unfortunately.

Have we checked anything regarding what customer noticed?

Thanks
Chris


Christian Mutnik
Support Account Manager (SAM)

NetApp
+49 (0) 6102-3658-3199 Direct Phone
+49 (0) 151-120 55 762 Mobile Phone


NetApp Technical Support:

US:               888 463 8277
EMEA:          00800 4463 8277
ASIA:            800 800 80 800

You may also get Support on the web at:
http://mysupport.netapp.com<http://mysupport.netapp.com/>
Out of office hours SAM assistance:

Please contact the SAM Major Incident Team (SMIT) for urgent issues.

Phone:   +49 (0) 89 900 59 4475
E-mail:    ***@***.******@***.***>




[A picture containing text  Description automatically generated]

[signature_3743553075]<https://www.facebook.com/NetApp>   [signature_1620217971] <https://www.instagram.com/netapp/>    [signature_1256517648] <https://www.youtube.com/netapp>    [signature_4105577864] <https://www.linkedin.com/company/netapp/>    [signature_215476164] <https://twitter.com/NetApp>




Diese e-Mail kann vertrauliche und/oder rechtlich geschützte Informationen enthalten. Wenn Sie nicht der richtige Adressat sind oder diese e-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese e-Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser e-Mail und ihrer Inhalte ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended addressee or have received this e-mail in error, please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
NetApp Deutschland GmbH, Sonnenallee 1, 85551 Kirchheim bei München,
Handelsregister: AG München HRB113907, VAT#: DE 182 196 996,
Geschäftsführer: Peter Hanke, Peter Wüst, James McGowan








Von: Megan Bock ***@***.***>
Antworten an: NetAppDocs/ontap-metrocluster ***@***.***>
Datum: Freitag, 4. November 2022 um 15:47
An: NetAppDocs/ontap-metrocluster ***@***.***>
Cc: Christian Mutnik ***@***.***>, Mention ***@***.***>
Betreff: Re: [NetAppDocs/ontap-metrocluster] Customer noticed that it is not needed to perform the task on both clusters (Issue #183)

NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



This issue will be closed on mon 14 nov due to lack of activity within the last 90 days. @chmutnik<https://github.com/chmutnik> - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp<https://github.com/jenatnetapp>, @netapp-ehoffman<https://github.com/netapp-ehoffman>

**Comment by netapp-aoife** [comment]
Hi Chris, Megan,  I am working with a SME on this issue. I will try to get this resolved before the Nov 14th close date. 

Thanks!
Aoife

**Comment by chmutnik** [comment]
Hi Aoife,

thanks a lot!

Best regards
Chris



Von: Aoife Hegarty ***@***.***>
Antworten an: NetAppDocs/ontap-metrocluster ***@***.***>
Datum: Montag, 7. November 2022 um 10:21
An: NetAppDocs/ontap-metrocluster ***@***.***>
Cc: Christian Mutnik ***@***.***>, Mention ***@***.***>
Betreff: Re: [NetAppDocs/ontap-metrocluster] Customer noticed that it is not needed to perform the task on both clusters (Issue #183)

NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Chris, Megan, I am working with a SME on this issue. I will try to get this resolved before the Nov 14th close date.

Thanks!
Aoife

**Comment by netapp-aoife** [comment]
Hi @ntap-bmegan , please keep this issue open past Monday. I will be able to close it before the end of next week.

**Comment by netapp-aoife** [comment]
Hi Chris, thanks again for providing this feedback. We have now addressed this issue in our documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_remove_unconfigure_mediator.html

**Comment by chmutnik** [comment]
Hi Aoife,
many thanks for your support!

Stay safe
Chris


Von: Aoife Hegarty ***@***.***>
Antworten an: NetAppDocs/ontap-metrocluster ***@***.***>
Datum: Dienstag, 22. November 2022 um 10:53
An: NetAppDocs/ontap-metrocluster ***@***.***>
Cc: Christian Mutnik ***@***.***>, Mention ***@***.***>
Betreff: Re: [NetAppDocs/ontap-metrocluster] Customer noticed that it is not needed to perform the task on both clusters (Issue #183)

NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Chris, thanks again for providing this feedback. We have now addressed this issue in our documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_remove_unconfigure_mediator.html
