### ISSUE TITLE
Is RCF update really necessary (might depend on RCF generator version)? 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#189]
Page: [Upgrade controllers from AFF A700/A900 to FAS9x00 in a MetroCluster IP configuration using switchover and switchback  (ONTAP 9.10.1 or later)](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_A700_to_A900_in_a_four_node_mcc_ip_us_switchover_and_switchback.html)

This might have to be double checked with Tom, but the document starts with "Update the MetroCluster switch RCF files before upgrading controllers". 

I'm just pasting 2 sample RCF files - one for A700 (transition from FC) and the other for A900: 

**A700 (transition from FC)**:

* Platforms : MetroCluster 1 : AFF-A320, FAS9000, AFF-A700, AFF-A800
*           : MetroCluster 1 : -Cluster Ports for Transition-
*
* Port Usage:
* Ports  1- 2: Intra-Cluster Node Ports, Cluster: MetroCluster 1, VLAN 101
* Ports  3- 4: Ports not used
* Ports  5- 6: 40G Ports for MetroCluster FC to IP transition
* Ports  7- 8: Intra-Cluster ISL Ports, local cluster, VLAN 101
* Ports  9-10: MetroCluster 1, Node Ports, VLAN 10
* Ports 11-12: Ports not used
* Ports 13-14: Ports not used
* Ports 15-20: MetroCluster-IP ISL Ports, VLAN 10, Port Channel 10
* Ports 21-24: MetroCluster-IP ISL Ports, VLAN 10, Port Channel 11, breakout mode 10gx4
* Ports 25-30: Ports not used
* Ports 31-36: Ports not used

**A900:** 

* Platforms : MetroCluster 1 : FAS8300, AFF-A400, FAS8700, AFF-A900
*
* Port Usage:
* Ports  1- 2: Intra-Cluster Node Ports, Cluster: MetroCluster 1, VLAN 101
* Ports  3- 4: Ports not used
* Ports  5- 6: Ports not used
* Ports  7- 8: Intra-Cluster ISL Ports, local cluster, VLAN 101
* Ports  9-10: MetroCluster 1, Node Ports, VLAN 10
* Ports 11-12: Ports not used
* Ports 13-14: Ports not used
* Ports 15-20: MetroCluster-IP ISL Ports, VLAN 10, Port Channel 10
* Ports 21-24: MetroCluster-IP ISL Ports, VLAN 10, Port Channel 11, breakout mode 10gx4
* Ports 25-30: Ports not used
* Ports 31-36: Ports not used

My point is, those look the same in terms of VLAN configuration. Is it possible that step in the guide was left from an old RFC generator release, which didn't show VLANs for A700? 

We're kind of stuck in the middle of an upgrade from A700 to A900 and going through the docs - while our customer hasn't re-applied any RCF files, it looks like this should work as it is (although I don't like how they've left the transition RCFs, but that's another thing). 

Thanks!

**Comment by viktorpenev** [comment]
Quick update, our issue was with the Node ports actually having to use 'switchport mode trunk' instead of 'switchport access...'. So RCF files had to be updated in the end. 

So this can maybe be a quick note that's it's not just VLAN related, but there are port configuration changes as well - the partner here was arguing for a day that the VLANs are okay and there is no issue with that, insisting that applying new RCF files won't change much.

**Comment by netapp-folivia** [comment]
Thanks, Viktor. I'll speak with the team to figure out the changes.

**Comment by netapp-folivia** [comment]
Hi Viktor, 

As you know, this section was reviewed -- the customer will have no issues when they follow all of the steps.

Thank you for your feedback as always! :)
