### ISSUE TITLE
Model typo in the title of the page (AFF A990)

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-metrocluster#191]
Page: [Upgrade controllers from AFF A700/FAS9000 to AFF A990/FAS9500 in a MetroCluster FC configuration using switchover and switchback (ONTAP 9.10.1 or later)](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_A700_to_A900_in_a_four_node_mcc_fc_us_switchover_and_switchback.html)

Title says "AFF A990/FAS9500". It should be "AFF A900/FAS9500".
The table of contents text is correct, BTW.

Also... I thought IE preferred using "or" instead of "/"?
i.e.
Upgrade controllers from AFF A700 or FAS9000 to AFF A900 or FAS9500 in a MetroCluster FC configuration using switchover and switchback (ONTAP 9.10.1 or later)

It's a minor thing... if you do end up changing to "or", please do this other topic, too:
https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_A700_to_A900_in_a_four_node_mcc_ip_us_switchover_and_switchback.html

**Comment by netapp-folivia** [comment]
Thank you! I'll fix the model number ASAP.
