### ISSUE TITLE
License installation section is missing

### ISSUE THREAD

**Issue by werenzo** [NetAppDocs/ontap-metrocluster#192]
Page: [Configuring Broadcom IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html)

Hello,
I've encountered a problem because I've applied RCF before installing licenze for additional port on the BES switches. I Think it would be useful to add a section that explain that additional licenses MUST be installed before to apply RCF.

I have been forced to restart configuration from the beginning.

Cheers

Lorenzo

**Comment by netapp-folivia** [comment]
Hi Lorenzo,

I'm currently working on this very update and it should be published soon.
Thanks for your feedback!

Olivia

**Comment by netapp-folivia** [comment]
Hi,

We have updated this section and added a new note about obtaining new licenses.
You can see the update here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html

Thanks for your feedback!
Olivia
