### ISSUE TITLE
Possibly a duplicate entry

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#194]
Page: [Configuring Broadcom IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html)

In the "Copy the RCF files to the switches" section we have: 

"copy sftp://user@FTP-server-IP-address/RcfFiles/switch-specific-RCF nvram:script BES-53248_v1.32_Switch-A1.txt nvram:script BES-53248_v1.32_Switch-A1.scr" 

This is where we're taking the file from: ftp://user@FTP-server-IP-address/RcfFiles/switch-specific-RCF

And this should be the destination, where we want to copy it to: nvram:script BES-53248_v1.32_Switch-A1.scr 

Is it necessary to also have "nvram:script BES-53248_v1.32_Switch-A1.txt", which seems to be the same, but just with a different file extension?

**Comment by netapp-folivia** [comment]
Hi Viktor,

Thanks for your feedback. We'll take a look and let you know.

Best,
Olivia

**Comment by netapp-folivia** [comment]
The example file path example in 2.a is now correct. You can see the update here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html

Thank you!
Olivia
