### ISSUE TITLE
Mediator link seems broken 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#195]
Page: [Upgrade controllers from AFF A700/FAS9000 to AFF A900/FAS9500 in a MetroCluster IP configuration using switchover and switchback  (ONTAP 9.10.1 or later)](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_A700_to_A900_in_a_four_node_mcc_ip_us_switchover_and_switchback.html)

In section "Restore Tiebreaker or Mediator monitoring" the Mediator link seems to be broken and displays: 

link:../install-ip/concept_mediator_requirements.html [Configuring the ONTAP Mediator service from a MetroCluster IP configuration] in the MetroCluster IP Installation and Configuration section.

**Comment by netapp-aoife** [comment]
Hi, thanks for raising this issue. We'll take a look and make the necessary changes.

**Comment by netapp-aoife** [comment]
Hi, the link has now been fixed here: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_A700_to_A900_in_a_four_node_mcc_ip_us_switchover_and_switchback.html#restore-tiebreaker-or-mediator-monitoring 

Thanks again for bringing this to our attention.
