### ISSUE TITLE
invalid parameter when configuring interface at loader prompt

### ISSUE THREAD

**Issue by danielpauldd** [NetAppDocs/ontap-metrocluster#196]
Page: [Netbooting and setting up ONTAP on the new controller module](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_netboot_and_set_up_ontap_on_the_new_controller_module_mcc.html)

When configuring an interface at loader prompt, the ifconfig parameter is `-gw` instead of `-gateway`

```
LOADER-A> ifconfig e0M -addr=172.20.93.100 -mask=255.255.0.0 -gateway=172.20.0.1
Invalid switch: -gateway
*** command status = Invalid parameter(-8)
LOADER-A> ifconfig e0M -addr=172.20.93.100 -mask=255.255.0.0 -gw=172.20.0.1
Network interface setup for IPv4
Device e0M:
    hwaddr D0-39-EA-xx-xx-xx, ipaddr 172.20.93.100, mask 255.255.255.0
    gateway 172.20.0.1, nameserver not set
    speed 1000 full duplex, loopback not supported
```

**Comment by netapp-aoife** [comment]
Hi, thanks for raising this issue. We'll look into this and make any necessary changes.

**Comment by netapp-aoife** [comment]
Hello, thanks again for bringing this to our attention. We have updated the formatting to make it clear that "gateway" is a variable and not the parameter. https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_netboot_and_set_up_ontap_on_the_new_controller_module_mcc.html
