### ISSUE TITLE
Typo in the Before you beging warning / maybe adding Cisco in the title to avoid confusion

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#199]
Page: [Upgrade RCF files on MetroCluster IP switches using CleanUpFiles](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_rcf_files_on_mcc_ip_switches_with_cleanupfiles.html)

When suggesting the order for upgrading the switches, Switch B_1 is listed twice:

![image](https://user-images.githubusercontent.com/84146725/185162635-1c0adfa5-0082-4e88-bc69-a21a9dce67d1.png)

**Comment by viktorpenev** [comment]
Just to avoid opening a separate ticket for that - before anyone tries to run this with a BES switch, can we add Cisco in the title?

**Comment by netapp-aoife** [comment]
Hi, thanks for bringing this to our attention. We'll investigate this and make any necessary changes.

**Comment by netapp-aoife** [comment]
Hi Viktor, thanks again for opening this issue. The issue has now been addressed in the documentation. 

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_rcf_files_on_mcc_ip_switches_with_cleanupfiles.html
