### ISSUE TITLE
Global search - MetroCluster spelling/capitalization

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-metrocluster#20]
@netapp-martyh , @netapp-aherbin , @dmajones -

There are instances of "Metrocluster" with a small c cluster in the docs, both in the content and the breadcrumbs.

Ben ran a quick search for me and reported 17 instances of “Metrocluster” in 9 files. I do not believe that includes the files where the breadcrumb values come from.

These need to be fixed. Should be "MetroCluster."

@netapp-ehoffman and @jenatnetapp for awareness

**Comment by dmajones** [comment]
@adamn-ntap - I have fixed the breadcrumbs for MCC. I believe the other instances will need to be fixed by @netapp-martyh  or @netapp-aherbin since it's within the actual content.

**Comment by jenatnetapp** [comment]
Thanks Danielle!

**Comment by dmajones** [comment]
You're welcome @jenatnetapp

**Comment by adamn-ntap** [comment]
@dmajones - thank you for making these changes. For future reference and so I can be educated, where are these values define? Are there specific files? Make me smarter.

**Comment by adamn-ntap** [comment]
@netapp-martyh and @netapp-aherbin - note that there is also a typo in the heading of one of the home page tiles - "ATTO bridge firmeare"

**Comment by netapp-aherbin** [comment]
Typo in home page heading for Metrocluster -> MetroCluster and tile - "ATTO bridge firmeare":  CORRECTED
@netapp-martyh will search and correct other instances of Metrocluster today.

**Comment by dmajones** [comment]
> @dmajones - thank you for making these changes. For future reference and so I can be educated, where are these values defined? Are there specific files? Make me smarter.

@adamn-ntap You're welcome. These values are defined in the Travis CI settings.
