### ISSUE TITLE
A doubt about topic 4

### ISSUE THREAD

**Issue by ACSantos47** [NetAppDocs/ontap-metrocluster#203]
Page: [Removing the MetroCluster FC controllers](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_remove_mc_fc_controllers.html)

Steps 2 and 3 use the data aggregate as example that will be delete, but on step 4 the aggregate used as example is root (node_B_1_aggr0). Is this correct?

Thank you!

**Comment by netapp-folivia** [comment]
Hi,

Thanks for raising this issue -- it doesn't look correct to me. I'll confirm and make the changes.

Thanks!
Olivia

**Comment by netapp-aoife** [comment]
Hello, thanks again for raising this issue. We have now addressed this in our documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_remove_mc_fc_controllers.html

**Comment by ACSantos47** [comment]
Hi guys!

Congratulations for this good job!

We are together!




Em qui., 15 de set. de 2022 às 14:08, Aoife Hegarty <
***@***.***> escreveu:
