### ISSUE TITLE
Adding warning for motherboard/NVRAM replacement during MCC-IP installation 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#204]
Page: [Overview](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html)

Following up on https://burtview.netapp.com/burts/1496296, I'm submitting this to update the MetroCluster IP installation guide to include something along the lines of: 

"if you need to replace a node and/or NVRAM card (anything that changes the SysID and/or SerialNo), then you must start from the beginning, assuming that the controllers are not pristine and had been used before. You must reinitialize all nodes at both the sites"

**Comment by netapp-folivia** [comment]
Thanks Viktor. We'll add this content and let you know when it's live.
Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Viktor,

I'm closing this issue as we are tracking the update in the BURT and the changes will be published very soon.

Thanks,
Olivia
