### ISSUE TITLE
Topic found in search but not in sidebar

### ISSUE THREAD

**Issue by netapp-aherbin** [NetAppDocs/ontap-metrocluster#206]
Page: [MetroCluster IP installation and configuration](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_deciding_whether_to_use_this_guide_mcc_ip_installation_and_configuration_guide.html)

While searching for info on MCC IP, this topic came up in search but is not found in the sidebar.

**Comment by netapp-martyh** [comment]
Thanks, Amanda, that file is a leftover and can be deleted -- assigning to Olivia.

**Comment by netapp-folivia** [comment]
This old topic has been removed from the folder.
Thanks,
Olivia
