### ISSUE TITLE
Typo in second table

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/ontap-metrocluster#209]
Page: [Choosing an upgrade or refresh method](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html)

There is a typo in the table in the section "Supported platform combinations for controller upgrade using switchover and switchback in a MetroCluster FC configuration"

The last row says "Current MetroCluster FC platform: A9900", it should say "A900" instead of "A9900"

**Comment by darkstar** [comment]
Also, the table (and indeed the whole page) is about "Upgrades", so the table cells where "current platform" is equal to "target platform" probably shouldn't be green but white (or maybe gray) instead

It makes no sense to say that the Upgrade from A400 to A400 is supported (it's not an upgrade then)

**Comment by netapp-folivia** [comment]
Thanks for raising this issue. We're actually working on updating the table right now. I spotted the typo earlier (that will be fixed ASAP). When we've finished the updates, I'll share the link showing the changes here.

Thanks,
Olivia

**Comment by netapp-folivia** [comment]
Hi,

This section has been revamped and the tables are revised: [https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html]

Thank you for your feedback and for helping us improve the docs!
Olivia
