### ISSUE TITLE
MCC repo and breadcrumb structure

### ISSUE THREAD

**Issue by jenatnetapp** [NetAppDocs/ontap-metrocluster#21]
I don't think the location is correct for the repo. It is under Cloud Docs (if I follow the breadcrumbs up, I arrive at the landing page that exists specifically for Cloud Products). 

![image](https://user-images.githubusercontent.com/48109805/115746182-f945b500-a348-11eb-9eea-dfac7bee3791.png)

I think we should follow the structure in use for Astra instead: 
![image](https://user-images.githubusercontent.com/48109805/115746003-d0bdbb00-a348-11eb-9d0f-d3a1c4c3aa4b.png)

**Comment by jenatnetapp** [comment]
@netapp-martyh 
@dmajones

**Comment by dmajones** [comment]
@jenatnetapp This issue is now resolved. 
![image](https://user-images.githubusercontent.com/53550488/115909295-9297c880-a428-11eb-91f5-6e98767a807e.png)

**Comment by netapp-martyh** [comment]
Thanks, Danielle!

**Comment by dmajones** [comment]
You're welcome, Marty!
