### ISSUE TITLE
Incorrect zoning

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#212]
Page: [Configuring the Brocade FC switches manually](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html)

RE: Zoning-for-fibrebridge-7500n-bridges-using-both-fc-ports
I think the following zoning is incorrect:
DrGroup 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1
&
DrGroup 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2

Can this please be corrected?

I can provide input if required.

**Comment by netapp-aoife** [comment]
Hello! Thank you for this feedback, we'll investigate this and update the documentation as needed.

**Comment by netapp-folivia** [comment]
Thank you. This section is currently in review and should be updated soon.

Thanks,
Olivia

**Comment by netapp-pcarriga** [comment]
Hi @tgoreham,
Thanks again for bringing this to our attention. The updates are published and you can view them here:
[Zoning for FibreBridge 7500N bridges using both FC ports](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html?q=modif#zoning-for-fibrebridge-7500n-bridges-using-both-fc-ports)
