### ISSUE TITLE
Step one says Brocade switches - believe this should be Broadcom

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#213]
Page: [Upgrade RCF files on MetroCluster IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html)

Hi,

As per the title, think Brocade should be changed to Broadcom.
Seems to be correct further down on the same page though.

Best Regards,
Erik

**Comment by netapp-aoife** [comment]
Hello, thank you for providing this feedback. We'll work to get this addressed in the documentation.

**Comment by netapp-aoife** [comment]
Hello, thanks again for bringing this to our attention. We have updated the documentation accordingly: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html#ensure-that-the-rcf-file-is-supported
