### ISSUE TITLE
HA interconnect information missing

### ISSUE THREAD

**Issue by werenzo** [NetAppDocs/ontap-metrocluster#217]
Page: [Cabling the controller peering, data, and management ports](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_cable_other_connections.html)

Hello,

following MCC-IP documentation for FAS8300 I initially didn't connected e0a and e0b. Then I got in doubt when I noticed storage failover errors before to complete configuration. Maybe it will be better to explain that in MCC-IP HA traffic will use IP switches and no direct interconnect is needed between controllers.

Kind Regards

Lorenzo

**Comment by netapp-folivia** [comment]
Thank you. This section is currently in review and should be updated soon.

Thanks,
Olivia

**Comment by netapp-pcarriga** [comment]
Hi @werenzo. we've added the following note to the 'Cabling the controller peering, data, and management ports' page:

_MetroCluster IP systems do not have dedicated high-availability (HA) ports. When using ONTAP Hardware Systems Documentation to install your platform, you should not follow the instructions to cable the cluster and HA ports._

Doc link: [Cabling the controller peering, data, and management ports](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_cable_other_connections.html)

Apologies for the delay in responding to this issue, and thanks again for helping us improve the customer documentation.
