### ISSUE TITLE
Update links from MCC Resources page to GitHub repo

### ISSUE THREAD

**Issue by jenatnetapp** [NetAppDocs/ontap-metrocluster#22]
All the links from https://www.netapp.com/support-and-training/documentation/metrocluster/# to doc content are now not working. 

Can we update them to point at the new GitHub content? At the very least… point to https://docs.netapp.com/us-en/ontap-metrocluster/index.html

**Comment by jenatnetapp** [comment]
@netapp-martyh 
@netapp-heatherk

**Comment by netapp-martyh** [comment]
Links have been updated on the resource page by Heather.
