### ISSUE TITLE
Instructions for second site are missing

### ISSUE THREAD

**Issue by tseroo** [NetAppDocs/ontap-metrocluster#220]
Page: [Powering off an entire MetroCluster FC configuration](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_off_an_entire_mcc_fc_configuration.html)

Although the title is 'Powering off an entire MetroCluster FC configuration' it does not even mention the second site of the MCC! Are the same steps required on the second site, or is e.g. disabling AUSO not needed as the other site is already down?

At least something like 'repeat steps 1-25 for second site' would be nice ...

**Comment by netapp-folivia** [comment]
Hi,

Thank you for your feedback.
We'll take a look at the procedure and will let you know what updates are made.

Best,
Olivia

**Comment by netapp-folivia** [comment]
Thank you. This section is currently in review and should be updated soon.

Thanks,
Olivia

**Comment by netapp-aoife** [comment]
Thanks again for bringing this to our attention. This issue has now been addressed in our documentation.
