### ISSUE TITLE
Is the SP setup missing from this page?

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/ontap-metrocluster#221]
Page: [Setting up ONTAP](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_setup_ontap.html)

Hi. Is the SP setup missing from this page? It's generally a good idea as far as I know. 

-Paul Stejskal

**Comment by netapp-folivia** [comment]
Hi,

We'll take a look at this page and let you know. Thanks for your feedback.

Best,
Olivia

**Comment by netapp-folivia** [comment]
Thank you. This section is currently in review and should be updated soon.

Thanks,
Olivia

**Comment by netapp-aoife** [comment]
Hi Chanda, this issue is still in progress. Please leave the issue open. Thanks!

**Comment by MrObvious** [comment]
Hi any update on this?

**Comment by netapp-aoife** [comment]
Hi @MrObvious, thanks again for this feedback. This issue is now addressed in the documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_setup_ontap.html
