### ISSUE TITLE
The procedure listed here is not correct

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#222]
**REOPENING [THIS ISSUE](https://github.com/NetAppDocs/ontap-metrocluster/issues/177)**

Page: [Manually assigning drives to pool 0](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_assign_pool0.html)

Step 8 states the following:

"Repeat these steps on the other nodes in the MetroCluster IP configuration."

But this is not correct. If you repeat these steps, you will wipe the partner node which you have already initialized.

Instead, 9a needs to be run on both nodes in the HA pair, and then 9b or option 4 can be run to configure the nodes after they have been initialized.

This mistake has caused great confusion for one of our customers recently.

**Comment by netapp-folivia** [comment]
Hi,

I'll check what happened the last time this issue was raised. I believe the document was verified by engineering and we closed the issue.
I'll let you know soon.

Thanks,
Olivia

**Comment by tgoreham** [comment]
Thanks Olivia,

Let me know if there are any questions.

Many Thanks,

Tom Goreham

**Comment by netapp-folivia** [comment]
Thank you for reopening the issue. I've spoken to Engineering, and we will update the documentation.
Separate issues have been opened above relating to the same problem. I'll let you know when the documentation is updated.

Thanks again for your feedback and taking the time to comment -- we do appreciate it!
Olivia
