### ISSUE TITLE
Update order question and VRF usage for getting the files on the switches 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#223]
Page: [Upgrade RCF files on Cisco IP switches using CleanUpFiles](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_rcf_files_on_cisco_ip_switches_with_cleanupfiles.html)

Hi all, 

We've tested the procedure last week on a lab system and it worked without any issues. Only thing that was a bit confusing at first was: 

4.c "Download files..." 

If you only run:

copy ftp://admin@10.10.10.10//ftp/rcf/cisco/Cleanup_NX3232C_v1.90_Switch-B2.txt bootflash: 

You get prompted to specify VRF (Virtual Routing and Forwarding) to be used. In our lab that had to be 'management'. Command could also be written as: 

copy ftp://admin@10.10.10.10//ftp/rcf/cisco/Cleanup_NX3232C_v1.90_Switch-B2.txt bootflash:  vrf management 

I'm not 100% sure if that would be applicable for every customer, but might save some time if we provide info on that. 

About the order in which the switches are updated, can we leave only the first suggestion - A1 > B1, etc, just to be consistent with https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html#ensure-that-the-rcf-file-is-supported and avoid any issues with upgrading local switches first. 

Thanks!

**Comment by netapp-folivia** [comment]
Thanks, Viktor! I wrote that procedure so I'm delighted! Your suggestions sound good.
I'll let you know once we've made the updates.

Best,
Olivia

**Comment by netapp-folivia** [comment]
These updates are now live: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_rcf_files_on_cisco_ip_switches_with_cleanupfiles.html

Thanks for your feedback, Viktor.

Olivia
