### ISSUE TITLE
Page is blank 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#224]
Page: [Preparing for the MetroCluster installation](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_prepare_for_the_mcc_installation.html)

Hi all, 

Following the "Considerations for configuring cluster peering" link from https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_cable_the_cluster_peering_connections.html seems to lead to a blank page: 

![image](https://user-images.githubusercontent.com/84146725/197955226-3ea73507-8701-48f1-b6e5-5b679bc69280.png)

Doesn't seem to be a browser issues at it happens in both Firefox and Chrome. 

Can anyone please take a look? Thanks!

**Comment by netapp-folivia** [comment]
Hi Viktor,

Yes, it looks like there's an error in the link. I'll update the link and let you know when it's published.

Thanks,
Olivia

**Comment by netapp-folivia** [comment]
Hi Viktor,

I have updated the link, and this will be published in the next day or two.

Thanks,
Olivia
