### ISSUE TITLE
-vserser is not an available option for cluster show

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap-metrocluster#225]
Page: [Expanding a four-node MetroCluster IP configuration to an eight-node configuration](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html)

cluster show -vserver Cluster

SiteA::> cluster show -vserver Cluster

Error: invalid argument "-vserver"

**Comment by netapp-folivia** [comment]
Thank you. again! I'll fix this today also.

Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Chanda,

Yes, I can begin working on this update very soon.

Thanks!
Olivia

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: [Expanding a four-node MetroCluster IP configuration to an eight-node configuration](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html).
