### ISSUE TITLE
"network port show -ipspace cluster" should have been "network port show -ipspace Cluster"

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap-metrocluster#226]
Page: [Expanding a four-node MetroCluster IP configuration to an eight-node configuration](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html)

The "cluster" in the command below should have been "Cluster"

network port show -ipspace cluster

**Comment by netapp-folivia** [comment]
Thank you, Jyhshing!
I'll fix this today.

Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Jyh-shing,

I have made this update and it will be published in the next couple of days.

Thanks,
Olivia

**Comment by netapp-jyhshing** [comment]
Thank you Olivia!
