### ISSUE TITLE
The information for clearing the node configuration for ADP is not accurate 

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap-metrocluster#227]
Page: [Restoring system defaults on a controller module](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_restore_defaults.html)

For the step to clear the node configuration when the system was configured for ADP, the question which prompts for confirmation has now changed to whether or not to abort the operation. 
As a result, the answer to the question should now be "no" instead of the "yes" as documented.
Also, the document should be updated to reflect the new question.

Here is a snippet of invoking 9a from boot menu and the updated the question.

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 9a
Pensando Offload Driver, ver 1.4.0-E-78
Pensando Ethernet NIC Driver, ver: 1.4.0-E-96
ionic_rdma ver 1.4.0-E-96 : Pensando RoCE HCA driver

Loaded OSAL module ***OS2SP configured successfully***pnso provider init started.
Notice : pnso card not detected.
hwo: Node is using hardware provider : 1.
cryptomod_fips: Executing Crypto FIPS Self Tests.
cryptomod_fips: Crypto FIPS self-test: 'CPU COMPATIBILITY' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-128 ECB, AES-256 ECB' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-128 CBC, AES-256 CBC' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-128 GCM, AES-256 GCM' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-128 CCM' passed.
cryptomod_fips: Crypto FIPS self-test: 'CTR_DRBG' passed.
cryptomod_fips: Crypto FIPS self-test: 'KDF' passed.
cryptomod_fips: Crypto FIPS self-test: 'SHA1, SHA256, SHA512' passed.
cryptomod_fips: Crypto FIPS self-test: 'HMAC-SHA1, HMAC-SHA256, HMAC-SHA512' passed.
cryptomod_fips: Crypto FIPS self-test: 'PBKDF2' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-XTS 128, AES-XTS 256' passed.
cryptomod_fips: Crypto FIPS self-test: 'Self-integrity' passed.
9a

	########## WARNING: AGGREGATES WILL BE DESTROYED ##########

This is a disruptive operation that applies to all the disks
that are attached and visible to this node.

Before proceeding further, make sure that:
1) The aggregates visible from this node do not contain
   data that needs to be preserved.
2) This option (9a) has been executed or will be executed
   on the HA partner node (and DR/DR-AUX partner nodes if
   applicable), prior to reinitializing any system in the
   HA-pair or MetroCluster configuration.
3) The HA partner node (and DR/DR-AUX partner nodes if
   applicable) is currently waiting at the boot menu.

Do you want to abort this operation (yes/no)?

**Comment by netapp-folivia** [comment]
This update is now live: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_restore_defaults.html

Thank you, Jyh-shing!
