### ISSUE TITLE
Single line of text on blank page

### ISSUE THREAD

**Issue by jenatnetapp** [NetAppDocs/ontap-metrocluster#23]
Another example of undesirable behavior discussed on an architect's thread where there are whole pages dedicated to one non-actionable line of text. 

![image](https://user-images.githubusercontent.com/48109805/115746605-4fb2f380-a349-11eb-83ab-5f72f72f4807.png)

**Comment by jenatnetapp** [comment]
@netapp-martyh 
@netapp-bcammett

**Comment by netapp-martyh** [comment]
This has been fixed with additional content on the page, however, soon this page will be eliminated as we implement new architecture standards for parent pages.
