### ISSUE TITLE
Need to refresh MetroCluster configuration first before creating mirrored data aggregate

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap-metrocluster#230]
Page: [Expanding a four-node MetroCluster IP configuration to an eight-node configuration](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html)

I am seeing an issue when trying to create mirrored aggregates while executing the following procedure.
 
Finalizing the addition of the new nodes
Steps:
1. Create mirror data aggregate on each of the new MetroCluster nodes.
2. Refresh the MetroCluster configuration.
2a. Enter advanced privilege mode
2b. Refresh the MetroCluster configuration 

SiteA::> storage aggregate create -aggregate aggr1_SiteA_03 -node SiteA-03 -diskcount 10 -mirror true -raidtype raid4 
 
Info: The layout for aggregate "aggr1_SiteA_03" on node "SiteA-03" would be:
      
      First Plex
      
        RAID Group rg0, 5 disks (block checksum, raid4)
                                                            Usable Physical
          Position   Disk                      Type           Size     Size
          ---------- ------------------------- ---------- -------- --------
          shared     5.0.0                     SSD-NVM           -        -
          shared     5.0.1                     SSD-NVM     862.9GB  862.9GB
          shared     5.0.2                     SSD-NVM     862.9GB  862.9GB
          shared     5.0.3                     SSD-NVM     862.9GB  862.9GB
          shared     5.0.4                     SSD-NVM     862.9GB  862.9GB
      
      Second Plex
      
        RAID Group rg0, 5 disks (block checksum, raid4)
                                                            Usable Physical
          Position   Disk                      Type           Size     Size
          ---------- ------------------------- ---------- -------- --------
          shared     6.0.1                     SSD-NVM           -        -
          shared     6.0.2                     SSD-NVM     862.9GB  862.9GB
          shared     6.0.3                     SSD-NVM     862.9GB  862.9GB
          shared     6.0.4                     SSD-NVM     862.9GB  862.9GB
          shared     6.0.5                     SSD-NVM     862.9GB  862.9GB
      
      Aggregate capacity available for volume use would be 2.88TB.
      
Do you want to continue? {y|n}: y
[Job 796] Job is queued: Create aggr1_SiteA_03.                                                                                            
 
Error: command failed: [Job 796] Job failed: Cannot create the aggregate because node "SiteA-03" is not fully configured for MetroCluster
       operations. MetroCluster configuration operations might be in progress. Wait a few minutes, then try the command again.
 
 
When the above two steps were reversed, i.e. refreshing the MetroCluster configuration first, the creation of mirrored data aggregates completed successfully.

**Comment by netapp-folivia** [comment]
Thank you, Jyh-shing. I'll make the update.
Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Jyh-shing,

I'm going to track all four issues for this procedure in the original GitHub issue that you created for this procedure: https://github.com/NetAppDocs/ontap-metrocluster/issues/225

Thanks,
Olivia
