### ISSUE TITLE
WRong privledge 

### ISSUE THREAD

**Issue by Ricknetapp** [NetAppDocs/ontap-metrocluster#231]
Page: [Upgrading controllers in a MetroCluster FC configuration using switchover and switchback](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html)

vserver override wont work on advanced privilege

**Comment by netapp-folivia** [comment]
Hi Rick,
Thanks for letting us know. Can you tell us what happens or what error you see?
I'll run your query by the engineers.

Thanks!
Olivia

**Comment by Ricknetapp** [comment]
Suspect this command will only work from 9.9 onwards

On 9.8 its not working
***@***.***

Rick Stuijfbergen
Senior Technical Support Engineer
MetroCluster

NetApp
00800 44638277 (EMEA/Europe)
***@***.******@***.***>

[A picture containing bird  Description automatically generated]<https://www.netapp.com/us/index.aspx>


***@***.***<https://www.facebook.com/NetApp>   ***@***.*** <https://www.instagram.com/netapp/>    ***@***.*** <https://www.youtube.com/netapp>    ***@***.*** <https://www.linkedin.com/company/netapp/>    ***@***.*** <https://twitter.com/NetApp>

**Comment by netapp-folivia** [comment]
Hi Rick,

I spoke to Engineering and they're going to test this command on an ONTAP 9.8 system. I'll let you know the outcome and of any doc. updates.

Thanks,
Olivia

**Comment by netapp-folivia** [comment]
Hi Rick,

I am closing this issue as we are tracking the update through the BURT (1532200).

Thanks,
Olivia
