### ISSUE TITLE
Need to bring down active SAN data LIF before LIF migration 

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap-metrocluster#232]
Page: [Removing a Disaster Recovery group](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_removing_a_disaster_recovery_group.html)

For the data LIF migration, an active SAN LIF cannot be migrated and requires the LIF to be brought down first.

   e. Migrate all data LIFs to home nodes in another DR group.
       network interface show -home-node old_node
       network interface modify -vserver svm-name -lif data-lif -home-port port-id

Here is what happened when attempted migration for an active iSCSI LIF to a different home node.

SiteA::> network interface modify -vserver Infra_SiteA -lif iscsi_SiteA_lif01a -home-node SiteA-03

Error: command failed: Cannot change the home-node or home-port of an active SAN data LIF

The SAN LIF to be migrated needs to be bring down first. See below for an example of migrating the iscsi_SiteA_lif01a LIF.

SiteA::> network interface show -vserver Infra_SiteA -data-protocol iscsi
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Infra_SiteA
            iscsi_SiteA_lif01a up/up 172.21.80.101/24 SiteA-01     a0a-3336 true
            iscsi_SiteA_lif01b up/up 172.21.81.101/24 SiteA-01     a0a-3337 true
            iscsi_SiteA_lif02a up/up 172.21.80.102/24 SiteA-02     a0a-3336 true
            iscsi_SiteA_lif02b up/up 172.21.81.102/24 SiteA-02     a0a-3337 true
            iscsi_SiteA_lif03a up/up 172.21.80.106/24 SiteA-03     a0a-3336 true
            iscsi_SiteA_lif03b up/up 172.21.81.106/24 SiteA-03     a0a-3337 true
            iscsi_SiteA_lif04a up/up 172.21.80.107/24 SiteA-04     a0a-3336 true
            iscsi_SiteA_lif04b up/up 172.21.81.107/24 SiteA-04     a0a-3337 true
8 entries were displayed.

SiteA::> network interface modify -vserver Infra_SiteA -lif iscsi_SiteA_lif01a -status-admin down                                                                                                                         
SiteA::> 
SiteA::> network interface modify -vserver Infra_SiteA -lif iscsi_SiteA_lif01a -home-node SiteA-03

SiteA::> network interface modify -vserver Infra_SiteA -lif iscsi_SiteA_lif01a -status-admin up   

SiteA::> network interface show -vserver Infra_SiteA -data-protocol iscsi
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Infra_SiteA
            iscsi_SiteA_lif01a up/up 172.21.80.101/24 SiteA-03     a0a-3336 true
            iscsi_SiteA_lif01b up/up 172.21.81.101/24 SiteA-01     a0a-3337 true
            iscsi_SiteA_lif02a up/up 172.21.80.102/24 SiteA-02     a0a-3336 true
            iscsi_SiteA_lif02b up/up 172.21.81.102/24 SiteA-02     a0a-3337 true
            iscsi_SiteA_lif03a up/up 172.21.80.106/24 SiteA-03     a0a-3336 true
            iscsi_SiteA_lif03b up/up 172.21.81.106/24 SiteA-03     a0a-3337 true
            iscsi_SiteA_lif04a up/up 172.21.80.107/24 SiteA-04     a0a-3336 true
            iscsi_SiteA_lif04b up/up 172.21.81.107/24 SiteA-04     a0a-3337 true
8 entries were displayed.

SiteA::>

**Comment by netapp-folivia** [comment]
Thank you, Jyh-shing! I'll confirm the update and make the changes.
Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Chanda, I'll begin working on this update today.

Thanks!
Olivia
