### ISSUE TITLE
During preparation for the removal of a DR group, the load-sharing mirrors cannot be moved. They need to be recreated.

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap-metrocluster#233]
Page: [Removing a Disaster Recovery group](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_removing_a_disaster_recovery_group.html)

1.Prepare for the removal of the DR group, if you haven’t already.
   a. Move all data volumes to another DR group.
   ...

As part of the preparation for the removal of the DR group, if there are load-sharing mirror volumes in the aggregates in the DR group, they cannot be moved. Instead new load-sharing mirror will need to be created on the other DR group.

Here is an example error message when attempting to move a load-sharing mirror volume.

SiteA::> vol move start -vserver Infra_SiteA -volume rootvol_SiteA_m01 -destination-aggregate aggr1_SiteA_03

Error: command failed: You cannot move a load-sharing destination volume. Instead, create a new load-sharing destination volume in the
       correct location. Then delete the load-sharing destination volume that you attempted to move. 

Perhaps we can insert another task for the preparation and insert it in between the existing tasks a and b.

1.Prepare for the removal of the DR group, if you haven’t already.
   a. Move all data volumes to another DR group.
   b. Recreate all load-sharing mirror volumes since they cannot be moved.
   ...

**Comment by netapp-folivia** [comment]
Thank you, Jyh-shing! I'll confirm the update and make the changes.
Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Chanda,

The resolution for this issue is now in progress. I hope to update the documentation soon.

Thanks!
Olivia

**Comment by netapp-aoife** [comment]
Hi Chanda, this is currently in review. Please keep the issue open. Thanks!
