### ISSUE TITLE
Update data LIF and cluster management LIF migration syntax information to include home-node

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap-metrocluster#234]
Page: [Removing a Disaster Recovery group](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_removing_a_disaster_recovery_group.html)

Update the data LIF and cluster management LIF migration command syntax in steps e and f below to include node information.

e. Migrate all data LIFs to home nodes in another DR group.
network interface show -home-node old_node

network interface modify -vserver svm-name -lif data-lif -home-port port-id

f. Migrate the cluster management LIF to a home node in another DR group.

network interface show -role cluster-mgmt

network interface modify -vserver svm-name -lif data-lif -home-port port-id

Node management and inter-cluster LIFs are not migrated.

For the data LIF and cluster management LIF migration syntax, use the following syntax instead since we are moving them to a different home node.

network interface modify -vserver svm-name -lif data-lif -home-node new_node -home-port port-id

network interface modify -vserver svm-name -lif cluster_mgmt -home-node new_node -home-port port-id

**Comment by netapp-folivia** [comment]
Thank you, Jyh-shing! I'll confirm the update and make the changes.
Best,
Olivia

**Comment by netapp-folivia** [comment]
I made this update today -- it should be published in the next few days.

Thanks,
Olivia

**Comment by netapp-jyhshing** [comment]
Thank you Olivia!

**Comment by netapp-folivia** [comment]
HI Jyh-shing,

This section is now [updated:](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_removing_a_disaster_recovery_group.htmlurl)

Thanks,
Olivia

**Comment by netapp-jyhshing** [comment]
Thank you Olivia!

By the way, the link for "updated" above has extra "url" at the end which needs to be removed to properly get to the page.
