### ISSUE TITLE
MetroCluster IP switch RCF update step needs to be included in the expanding a four node MetroCluster IP configuration documentation

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap-metrocluster#235]
Page: [Expanding a four-node MetroCluster IP configuration to an eight-node configuration](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html)

The documentation is missing a step to update the RCF files on the MetroCluster IP switches.

I reached out to Mr. _T and here is his feedback.

Please include the RCF update process in between the two steps Mr. _T indicated below. 

=====
Yes --- between
https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html#preparing-the-new-controller-modules
Preparing the new controller modules
And
Joining the new nodes to the clusters

The RCF file need to be upgraded/changed. I don’t know why that is missing in that procedure.
 
Thanks,
_T
=====

**Comment by netapp-folivia** [comment]
Thank you, Jyh-shing! I'll confirm the update and make the changes.
Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Jyh-shing,

I'm going to track all four issues for this procedure in the original GitHub issue that you created for this procedure: https://github.com/NetAppDocs/ontap-metrocluster/issues/225

Thanks,
Olivia
