### ISSUE TITLE
generate fr and de - 12780

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/ontap-metrocluster#237]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
I've set permissions on German but the dictionary isn't back. I haven't seen any GH Pages errors so far, but when the dictionary comes back, make sure the setting is correct or bounce this back to me to check it.
