### ISSUE TITLE
Need consistent node names in the MetroCluster transition document

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#239]
Page: [Configure the MetroCluster for transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html)

Hi,

In the section "Joining the MetroCluster IP nodes to the clusters", steps 1 and 2 refer to nodes as "node_A_1-IP", "node_A_2-IP", "node_B_1-IP" and "node_B_2-IP".

Then in section "Configuring intercluster LIFs, creating the MetroCluster interfaces, and mirroring root aggregates", there's inconsistency in the naming.
Step 4, in the first example output new IP nodes are named node_[AB]_[34]-IP.
In the 2nd example of step 4, they are node_[AB]_[12]-IP.

It would make sense to have the same names for the IP nodes throughout the document.
My preference would be:
node_A_3-IP
node_A_4-IP
node_B_3-IP
node_B_4-IP

This way the node number will reflect the actual node number as the starting point is a 2-node cluster.

Thanks,
Erik

**Comment by netapp-folivia** [comment]
Hi Erik,

We have fixed the node names as you advised. You can see the changes here: [https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html#configuring-intercluster-lifs-creating-the-metrocluster-interfaces-and-mirroring-root-aggregates] Thank you for your feedback and interest in the docs!

Best,
Olivia

**Comment by estarz** [comment]
Thanks,

Had a quick look and it looks much better and easier to understand.

Having said that I noticed a few instances of 1-IP and 2-IP:
***@***.***
…
[Text  Description automatically generated]

Then on Mirror root aggregates, the aggregate name contains “-“ (dash) which is not a valid character in aggregate names….
[Graphical user interface, application  Description automatically generated]
..

[Table  Description automatically generated]

Finally I found an instance of node name 1-new:
[Graphical user interface, text  Description automatically generated]


Shall I open up a new github issue for these things?

From: Olivia Fitzgerald ***@***.***>
Date: Thursday, 5 January 2023 at 12:42
To: NetAppDocs/ontap-metrocluster ***@***.***>
Cc: Stjerna, Erik ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/ontap-metrocluster] Need consistent node names in the MetroCluster transition document (Issue #239)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Erik,

We have fixed the node names as you advised. You can see the changes here: [https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html#configuring-intercluster-lifs-creating-the-metrocluster-interfaces-and-mirroring-root-aggregates] Thank you for your feedback and interest in the docs!

Best,
Olivia

**Comment by netapp-folivia** [comment]
HI Erik,

No, that's fine - we'll use the same issue. Thanks for noticing!

Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi,

This topic has been updated to correct the node names. Please let me know if you spot anything else amiss.
[Configure the MetroCluster for transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html#sending-a-custom-autosupport-message-prior-to-maintenance)

Best,
Olivia
