### ISSUE TITLE
AFF-A400 HA Interconnect Cabling MCCIP 

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#240]
Page: [Cabling the controller peering, data, and management ports](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_cable_other_connections.html)

Noticed that this page links to the relevant non-MCCIP documentation for system cabling: [AFF and FAS System Documentation](https://docs.netapp.com/us-en/ontap-systems/)

If we look at the [A400 detailed guide](https://docs.netapp.com/us-en/ontap-systems/a400/install-detailed-guide.html) & [PDF](https://docs.netapp.com/us-en/ontap-systems/media/PDF/215-14510_2020_09_en-us_AFFA400_ISI.pdf), we see that e0a/e0b are always reserved for the HA interconnect (no exceptions for MCCIP are mentioned).

This is strange because when you install an AFF-A400 system for MCCIP, ports e0a/e0b are available for hosting data LIFs (usually in Default IPSpace), this should be highlighted as an exception in the documentation.

Here is an [example](https://smartsolve.netapp.com/#cdv?refasup=2022112616251637&view=horizontal&section=IFSTAT-A&asupids=2022112616251637) from one of our customers.

It has been raised by multiple Field Engineers that PS have been cabling the systems 'as documented' which means they have 2 wasted ethernet ports per node that could instead be used for front-end operations.

So... my questions are as follows:

1. Would we support the use of e0a/e0b as data ports in MCCIP configs? (Don't see why not, but obviously we need this checked).
2. If supported - Please can we get the documentation updated to include an exception for e0a/e0b on the AFF-A400 when used in a MetroCluster IP config? It should just state that they can be used as front-end ports instead of being reserved for the HA interconnect.

**Comment by netapp-folivia** [comment]
Hi Tom,

Thanks for your feedback. I'll confirm the changes and update the documentation.

Best,
Olivia

**Comment by netapp-aoife** [comment]
Hi @netapp-chandaj , this is currently in progress. Please keep this issue open. Thanks!

**Comment by netapp-aoife** [comment]
Hi Chanda, this is still in progress. Please leave this issue open.

**Comment by netapp-aoife** [comment]
Hi @tgoreham thanks again for raising this issue. This issue was addressed in the following documentation: https://docs.netapp.com/us-en/ontap-systems/a400/install-detailed-guide.html#step-2-install-the-hardware
