### ISSUE TITLE
Current procedure risks VIFMGR OOQ

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#241]
Page: [Move the local cluster connections](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html)

Step 1 in [Moving the local cluster connections when using new IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#moving-the-local-cluster-connections-when-using-new-ip-switches) _should_, in theory, be correct, but due to known BURTs with VIFMGR going OOQ (1127799/1496639) it risks an outage.

One of our customers hit this in the field and it has really shaken their confidence in their new MetroCluster IP solution and they haven't even migrated data to it yet.

In order to avoid exposing more customers to this issue whilst engineering is looking into improving the resiliency of the cluster network, I think we should consider linking to the relevant cluster switch migration guide instead of recommending the current steps as they are too risky.

E.g: [How to migrate from an older Cisco switch to a Cisco Nexus 9336C-FX2 cluster switch](https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/migrate-to-9336.html). This guide contains the necessary steps to prevent the cluster network from going OOQ and it is an already validated procedure.

**Comment by netapp-folivia** [comment]
Hi Tom,

Thanks for raising this issue. I've spoken to Engineering, and they are already aware of this issue. I'll contact you soon to let you know the status.

Thanks,
Olivia
