### ISSUE TITLE
Review health after configuring new nodes

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#242]
Page: [Configure the MetroCluster for transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html)

At the end of this section of the guide I think it would be wise to have some checks to verify the health of the new MCCIP nodes before we start migrating data to them.

I have had numerous cases now and there are multiple bugs out there (1305232/1307431 for example) and I even see we had a DOCBURT (1393238) for ordinary MCCIP installs (not FC to IP transition) suggesting to reboot the nodes after install.

The checks I would propose are the likes of (more can be added where required):
```
metrocluster check run/show
metrocluster interconnect mirror show
metrocluster interconnect adapter show
storage failover show
```

This is simply to verify HA and give you the chance to reboot the nodes should they have any anomalies before passing the 'point of no return' when the DR group containing the FC nodes is removed. 

At that point, it becomes tricky to reboot the nodes without causing an outage if there is no HA or DR available.

**Comment by netapp-folivia** [comment]
Hi Tom,

Thank you for raising this issue. I've checked with Engineering, and they are currently working on this issue. I'll email you directly with any updates.

Thanks,
Olivia
