### ISSUE TITLE
Additional check before moving volumes

### ISSUE THREAD

**Issue by netappmf** [NetAppDocs/ontap-metrocluster#243]
Hello all

is it possible to add another check to the Install Guide? We've noticed this in several installations so far and it would prevent having a downtime later. 

In the Section "Finalizing the addition of the MetroCluster IP nodes" before "Move the MDV_CRS volumes from the old nodes to the new nodes in advanced privilege." a "Storage failover show" should be issued to check if there is any NVRAM issue on the Metro-IP nodes.

cluster::*> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node_FC_1    Node_FC_2    true     Connected to Node_FC_2
Node_FC_2    Node_FC_1    true     Connected to Node_FC_1
Node_IP_1    Node_IP_2    false    Waiting for Node_IP_2, Takeover is
                                       not possible: Storage failover
                                       interconnect error, NVRAM log not
                                       synchronized, Disk inventory not
                                       exchanged
Node_IP_2    Node_IP_1    false    Waiting for Node_IP_1, Takeover is
                                       not possible: Storage failover
                                       interconnect error, NVRAM log not
                                       synchronized, Disk inventory not
                                       exchanged

If it looks like this and you start moving Volumes you are not able to finish the transition at the end and you might need to reboot the new nodes that already contain data. So to prevent this everyone should check the storage failover state before moving data and it has to be like this

cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
Node_FC_1    Node_FC_2    true     Connected to Node_FC_2
Node_FC_2    Node_FC_1    true     Connected to Node_FC_1
Node_IP_1    Node_IP_2    true     Connected to Node_IP_2
Node_IP_2    Node_IP_1    true     Connected to Node_IP_1

If not the new Nodes have to be rebooted to fix this

**Comment by netapp-folivia** [comment]
Hi,

Thank you for feedback. I'll confirm the update and make any necessary changes. I'll let you know here when it's complete.

Thanks!
Olivia

**Comment by netapp-aoife** [comment]
Hi Chanda, this issue is currently in review. Please leave the issue open. Thanks!

**Comment by netapp-aoife** [comment]
Hi there, this issue has now been addressed here: https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html#finalizing-the-addition-of-the-metrocluster-ip-nodes

Thanks again for helping us improve our documentation!
