### ISSUE TITLE
G630 switch is missing

### ISSUE THREAD

**Issue by massa007** [NetAppDocs/ontap-metrocluster#244]
Page: [AFF A900 or FAS9500 - Brocade port usage for ISLs in an MetroCluster configuration running ONTAP 9.10.1 or later](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_AFF_A900_brocade_port_ISLs.html)

G630 switch is missing

**Comment by netapp-folivia** [comment]
Hi,

Thanks for bringing this to our attention. I'll confirm the update and make the necessary changes.

Thanks!
Olivia

**Comment by netapp-folivia** [comment]
Hi,

The switch has been added to the table: https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_AFF_A900_brocade_port_ISLs.html

Thank you!

Best,
Olivia
