### ISSUE TITLE
Add steps for zoning/RCF and applying licenses 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#249]
Page: [Replacing a Brocade FC switch](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_brocade_fc_switch_mcc.html)

Hello everyone, 

Hope this message finds you well. In Step 3c there's a note suggesting to skip zoning config at that point, but there is no additional information on that later in the document. 

Additionally, there is no mention of applying any licenses on the newly installed switch (they could be transferred from the impaired one). 

Best regards, 
Viktor

**Comment by netapp-folivia** [comment]
Hi Viktor,

We're doing well! Thank you for this feedback. 
We'll take a look and make the necessary changes.

Thanks!
Olivia

**Comment by netapp-martyh** [comment]
No update at this time. Reassigning to Aoife in Olivia's absence.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev thanks again for raising this issue. This has now been addressed in the documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_brocade_fc_switch_mcc.html
