### ISSUE TITLE
Step 9 container-type 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#252]
Page: [Configure the MetroCluster for transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html)

Hello everyone, 

Just got a feedback from a customer about the KB - they got to step 9 and were checking the disk assignment, but were wondering why they don't see 'remote' as a container-type, but 'shared'. 

They use ADP, so the drives are partitioned and the 'shared' container-type is expected - https://docs.netapp.com/us-en/ontap-cli-9111/storage-disk-show.html#parameters 

Can we add a note for that in the documentation? 

Thanks, 
Viktor

**Comment by netapp-folivia** [comment]
Thanks, Viktor! I'll update you here with progress.
Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Viktor,

We added the note. [Configuring intercluster LIFs, creating the MetroCluster interfaces, and mirroring root aggregates](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html#configuring-intercluster-lifs-creating-the-metrocluster-interfaces-and-mirroring-root-aggregates) 

Thanks again for your feedback!

Best,
Olivia
