### ISSUE TITLE
Link to supported platforms on this page is a 404...

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#255]
Page: [Requirements for nondisruptive FC-to-IP transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_requirements_for_fc_to_ip_transition_mcc.html)

This: https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_supported_platforms_for_transition.html => 404

Best Regards,
Erik

**Comment by estarz** [comment]
I see on: https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_supported_platforms_for_transition.html

There is a redirect: pageRedirect("https://docs.netapp.com/us-en/transition/concept_choosing_your_transition_procedure_mcc_transition.html");

There is a "ontap-metrocluster missing in the beginning of that URL.
Should be: https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html

**Comment by netapp-folivia** [comment]
Thanks, Erik! We'll fix this.

Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Erik,

I'm closing this issue as the same problem was raised in issue 264 and the update will be published soon.

Thanks,
Olivia
