### ISSUE TITLE
example switch output is not consistent with previous steps

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#256]
Page: [Move the local cluster connections](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html)

Section "Moving the local cluster connections when using new IP switches", step 3, have us run "show int br"

The example output shows ports 5,6 are down but in step 2 we just connected the FC-nodes there. They should be up.
Also ports 1,2 and 9,10 are shown as up. This is where the new IP nodes will be connected in a later stage of the procedure. I would have expected these ports to be down...

Best regards,
Erik

**Comment by estarz** [comment]
Meant to say 1,2 and 9,10 should probably not be shown as up. (7,8 are Interswitch Links so should be up)

**Comment by netapp-folivia** [comment]
Hi Erik,

Thank you. We'll take a look and make the necessary changes.

Best,
Olivia

**Comment by netapp-folivia** [comment]
We have updated the example to remove the irrelevant port information.
Thank you for your interest in the docs!

Thanks,
Olivia
