### ISSUE TITLE
Download link for Cumulus FW

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#257]
Page: [Configure the NVIDIA IP SN2100 switch](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_nvidia.html)

Could we consider getting a link to download the switch firmware in this doc? I assume it will be a link external to the NetApp Support Site Downloads page, but we have one for the [Cisco switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software) so I suppose one in this doc would also be helpful.

**Comment by netapp-folivia** [comment]
Hi,

Thanks for this idea. We'll update the documentation soon.

Best,
Olivia

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: [Reset the switch using the Cumulus install option](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_nvidia.html#reset-the-switch-using-the-cumulus-install-option)
