### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sgalla-netapp** [NetAppDocs/ontap-metrocluster#259]
Page: [Refreshing a four-node MetroCluster IP configuration (ONTAP 9.8 and later)](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html)

Link for "[Choosing a system refresh method]" is incorrect.

**Comment by netapp-folivia** [comment]
Thank you! I'll fix this right away.
