### ISSUE TITLE
Configuring SNMPv3 in a MetroCluster configuration - AES-256

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#26]
Page: [Configuring the MetroCluster software in ONTAP](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html)

The **Configuring SNMPv3 in a MetroCluster configuration** section states the following:

> ONTAP currently supports AES-128 and AES-256 encryption.

But when configuring the SNMP user in ONTAP this is what is seen:

`Which privacy protocol do you want to choose (none, des, aes128) [none]:`

There is no option for AES256 when configuring this user. I tried this on two of our lab systems running 9.8RC1 and 9.7P8.

Can someone please confirm if AES256 is actually supported for configuring SNMP users or is this information incorrect?

**Comment by netapp-martyh** [comment]
Spoke with Tom, he says:
We are deliberately taking the switch offline, then update the FOS and then take it online again. This is the safest way doing it and this is what is qualified.

If people are using other steps and/or commands – they are not supported.

Thanks,
_T

**Comment by netapp-martyh** [comment]
My mistake - closed the wrong issue. Will follow up on this issue again.

**Comment by netapp-martyh** [comment]
Removed AES-256 in hotfix, 2021.11.21.
