### ISSUE TITLE
There is a 404 when following the link "Supported platforms for nondisruptive transition"

### ISSUE THREAD

**Issue by nmillot** [NetAppDocs/ontap-metrocluster#263]
Page: [Requirements for nondisruptive FC-to-IP transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_requirements_for_fc_to_ip_transition_mcc.html)

There is a 404 when following the link "Supported platforms for nondisruptive transition":
[Supported platforms for nondisruptive transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_supported_platforms_for_transition.html)"

**Comment by netapp-aoife** [comment]
Hello. Thank you for bringing this to our attention. We'll get this fixed and notify you when it's complete.

Thanks,
Aoife

**Comment by netapp-aoife** [comment]
Hi there, this issue has now been addressed in our documentation. Thanks again for raising this issue.
