### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#264]
Page: [Requirements for nondisruptive FC-to-IP transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_requirements_for_fc_to_ip_transition_mcc.html)

[Supported platforms for nondisruptive transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_supported_platforms_for_transition.html) link is broken in the document.

I suppose this should be the table that's supposed to be linked there - https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html

**Comment by netapp-aoife** [comment]
Thanks Viktor. We'll get this fixed and let you know when it's complete.

**Comment by netapp-aoife** [comment]
Hi Viktor, this issue has now been fixed in the documentation. Thanks again for raising this issue.
