### ISSUE TITLE
Port cabling for Cisco 9132T doesn't match the RCFs 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#265]
Page: [Port assignments for FC switches when using ONTAP 9.1 or later](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html)

Hi everyone, 

This is related to Burt #1532007. I've checked the RCFs we provide for Cisco 9132T switches - https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab/download/63467/Cisco_9132T - and the config there doesn't seem to match what we have documented here. 

While there doesn't seem to be anything wrong in the RCFs by themselves and they seem to have been recently updated, it might be a bit easier (quicker) to update the doc pages to match the RCF cabling. 

In the burt I've mentioned a few things, which seem off, but if necessary I can paste the details here as well. 

I have a customer in the middle of an FC installation, who noticed this, so they want to make sure everything is okay with the system. 

Thanks!

**Comment by viktorpenev** [comment]
On the same topic, the same can be said for https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_switch_ports_required_for_a_eight_node_mcc_configuration_with_array_luns.html#overall-cabling-guidelines-with-array-luns as those configs use the same switches, but that could be a separate ticket, if needed.

**Comment by netapp-folivia** [comment]
Hi Viktor, 

Thank you we'll take a look and update the docs as needed.

Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Viktor, 

Just to let you know this issue is being tracked internally in BURT. I will forward you the details if you need them for reference.

Thanks!
Olivia
