### ISSUE TITLE
Add note for MetroClusters with only one data aggregate per site

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#267]
Page: [Configure the MetroCluster for transition](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html)

Hi,

Performed a 4-8-4 FC to IP yesterday, up to the step where customer will start to move data.

Got stuck on the "metrocluster configure" as ONTAP complained about there were not enough mirrored aggregates per site.
It's a quite common configuration at least for older MCC that customer has decided to use only create one data aggregate per site.
When that MCC is initially created you need to use advanced privilege and add "-allow-with-one-aggregate true" to the "metrocluster configure" command.

It would be nice if this was mentioned in the transition documentation as well to remove any confusion and unnecessary angst.

Thanks,
Erik

**Comment by netapp-folivia** [comment]
Hi Erik,

Thank you for your feedback. I'll talk to those who know and update the docs accordingly.

Thanks,
Olivia

**Comment by netapp-folivia** [comment]
Hi Erik,

We have added new steps for when there is only one data aggregate per site: [Finalizing the addition of the MetroCluster IP nodes](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_configure_transition.html#finalizing-the-addition-of-the-metrocluster-ip-nodes)

Thanks,
Olivia
