### ISSUE TITLE
High-availability configuration link not found

### ISSUE THREAD

**Issue by nmillot** [NetAppDocs/ontap-metrocluster#269]
Page: [Understanding MetroCluster data protection and disaster recovery](https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html)

Chapter "How local HA data protection works in a MetroCluster configuration"
Related information
[High-availability configuration](https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-hacg/home.html) link not found

**Comment by netapp-aoife** [comment]
Hi, thanks for raising this issue. We'll work towards getting this addressed and let you know when the documentation is updated.

**Comment by netapp-folivia** [comment]
Hi,

We've fixed the faulty link -- thank you for letting us know.
[Understanding MetroCluster data protection and disaster recovery](https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#how-local-ha-data-protection-works-in-a-metrocluster-configuration)

Best,
Olivia
