### ISSUE TITLE
Mixing of initiators in the zoning config

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#270]
Page: [Configuring the Brocade FC switches manually](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html)

In the zoning tables for "Zoning for FibreBridge 7500N bridges using both FC ports" we should be using 4 initiators (one from each node) + One port connecting to an FC-to-SAS bridge FC port. 

Examples with 0a/0c ports look okay - e.g.,  we have 1x 0a port from each controller and in 4n MCC. 

But for the 0b/0d, we start to mix those in the same table, while that should follow the same scheme as above. 

4x 0b > bridge_A_1a FC2 
4x 0d > bridge_A_1b FC2

**Comment by netapp-folivia** [comment]
Thanks, Viktor. We'll take a look at this section and make the updates.

Best,
Olivia

**Comment by netapp-pcarriga** [comment]
Hi @viktorpenev, 
The updates are published and you can view them here:
[Zoning for FibreBridge 7500N bridges using both FC ports](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html?q=modif#zoning-for-fibrebridge-7500n-bridges-using-both-fc-ports)
Thanks again for bringing this to our attention.
