### ISSUE TITLE
Make it more obvious which site to run forced switchover from

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#273]
Page: [Performing a forced switchover after a disaster](https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/task_perform_a_forced_switchover_after_a_disaster.html)

I had a look at this document and although for most people it would go without saying - to make this procedure as air-tight as possible - I think we need to put a clear statement regarding which site the `metrocluster switchover -forced-on-disaster true` command should be run from (the "surviving" site).

**Comment by netapp-folivia** [comment]
Hi Tom,

Thanks for letting us know. We'll make the update.

Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Tom,

We clarified the step to indicate that you perform the switchover command at the surviving site: [Performing a forced switchover](https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/task_perform_a_forced_switchover_after_a_disaster.html#performing-a-forced-switchover)
Thanks for the feedback.

Best,
Olivia
