### ISSUE TITLE
Procedure for adding shelves up to date?

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#274]
Page: [Hot-adding a stack of SAS disk shelves to an existing pair of FibreBridge 7500N bridges](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_hot_add_a_stack_to_exist_7500n_pair.html)

Hi,

this procedure is written explicitely for an ATTO 7500 fiber bridge. This is EOA for some time and the successor 7600 is used in recent configurations.
Does this procedure apply 1:1 on the 7600 as well?
If yes, it should explicitley be called out.
If not, can it please be added?

Cheers, Niels

**Comment by netapp-folivia** [comment]
Hi Niels,

Thanks for the feedback. I'll find out and make the necessary updates.

Best,
Olivia

**Comment by netapp-folivia** [comment]
Hi Niels,

We are currently updating this topic -- you can track the updates in BURT 1498347.
I'll inform you when the updates are published.

Thanks again for your great feedback!

Best,
Olivia
