### ISSUE TITLE
Multiple issues regarding "metrocluster configure -refresh true" command

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#276]
Page: [Implementing the MetroCluster configuration](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_implement_the_mcc_configuration_mcc_refresh_mcc_expansion.html)

Hi,

Performed an expansion and notice a couple of oddities in this doc page.

<img width="1670" alt="Screenshot 2023-03-16 at 09 45 38" src="https://user-images.githubusercontent.com/2291693/225563655-327ad995-f55c-40a7-abcc-2bc514d733f6.png">

In the About this task section, the first line reads:
You issue the metrocluster configure -refresh true command once, **on one of the newly added nodes**, 
So how do I run a cluster command on a specific node? Via node management on that node? By using the non-mentioned -node flag on the metrocluster configure command?
My assumption is that the part "on one of the newly added nodes" should be taken out and it does not matter "where" I run the command.

Then in the "Steps", step 1b is confusing.
It says "on one of the nodes" and the previous About section said "You do not need to issue the command on each of the sites or nodes".
But here is looks like the command is run twice.
And the cluster prompts look weird, it's like it's 2 different clusters, controller_A_2::*> and controller_A_4::*>
Given what the name says, it looks like the are potentially node names?
And again, if so, where is the instruction to run a cluster shell command "on a specific node"?
My assumption is that the command should be run *once* on the cluster.

But then onto what actually happens when you run the metrocluster config -refresh true is that you get a warning that all your metrocluster configuration will be overwritten and you are prompted if you want to go ahead.
Since the docs don't give guidance on that you do get a warning and what to respond, it's easy to get stuck here.

<img width="566" alt="Screenshot 2023-03-16 at 09 47 31" src="https://user-images.githubusercontent.com/2291693/225563722-bba966ee-d9f5-4b0e-8c9a-572f319c46b6.png">

Finally in steps 3a and 3b, the example output contains "Configuration: IP fabric" which I would not expect when expanding a MetroCluster FC.

**Comment by netapp-folivia** [comment]
Hi,

Thank you for your feedback. We'll review your comments and revise the documentation as needed.

Best,
Olivia

**Comment by estarz** [comment]
Hi Olivia,

The only question mark, if it is the docs or our specific procedure, is the warning – if that is specific for 8->12 node.
And as far as that warning goes, we responded yes and we now have a happy 12-node MCC.

All other issues I brought up apply to 4->8 as per the docs.
So maybe you want to have another look at the wording “run on one node” etc.

Thanks,
Erik

From: Olivia Fitzgerald ***@***.***>
Date: Thursday, 16 March 2023 at 12:53
To: NetAppDocs/ontap-metrocluster ***@***.***>
Cc: Stjerna, Erik ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/ontap-metrocluster] Multiple issues regarding "metrocluster configure -refresh true" command (Issue #276)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Closed #276<https://github.com/NetAppDocs/ontap-metrocluster/issues/276> as completed.

**Comment by netapp-folivia** [comment]
Hi Erik,

Thanks -- I'll create a Jira ticket and add you as a 'watcher'.

Best,
Olivia
