### ISSUE TITLE
Move all flash cache modules and wrong system model

### ISSUE THREAD

**Issue by Kenneth-borg** [NetAppDocs/ontap-metrocluster#277]
Page: [Upgrade controllers from AFF A700/FAS9000 to AFF A900/FAS9500 in a MetroCluster FC configuration using switchover and switchback (ONTAP 9.10.1 or later)](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_A700_to_A900_in_a_four_node_mcc_fc_us_switchover_and_switchback.html)

"Do not transfer any parts from the AFF A700 or A900 controller module and NVS to the AFF A900 or FAS9500 controller module. "

should be 
"Do not transfer any parts from the AFF A700 or FAS9000 controller module and NVS to the AFF A900 or FAS9500 controller module. "

also for the FAS9000 to FAS9500 system we should move over flashcache cards in slot 6. 
as we do in the ARL doc for
[Use "system controller replace" commands to upgrade AFF A700 to AFF A900 running ONTAP 9.10.1 or later](https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/index.html)

the text in MCC doc give a picture that no card should be moved over "Do not transfer any parts from the AFF A700 or A900 **controller module and NVS** to the AFF A900 or FAS9500 controller module. "

**Comment by netapp-aoife** [comment]
Hi Kenneth, thank you for raising this issue. We'll review this feedback and let you know when the documentation is updated.
