### ISSUE TITLE
align with the KB

### ISSUE THREAD

**Issue by aknetapp** [NetAppDocs/ontap-metrocluster#28]
Page: [Removing a Disaster Recovery group](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_removing_a_disaster_recovery_group.html)

maybe we should align the additional steps from KB https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_remove_a_DR-Group_from_a_MetroCluster with this doc.

**Comment by netapp-folivia** [comment]
Hi! The documentation is now updated. You can view the updates here: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_removing_a_disaster_recovery_group.html
