### ISSUE TITLE
Changes to power-on procedure from BURT 1539230

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#281]
Page: [Powering off and powering on a data center](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_on_and_power_off_a_data_center.html)

Thomas Wenzel commented on the power-on procedure when reviewing BURT 1539230:

"While these steps got somewhat mangled – the order described doesn’t match what ASUP tells me.
Ideally – the proper sequence is:
-	Power on switches, verify ISL
-	Disable ISL
-	Powere on controllers (no storage yet there --- ensures they drop to LOADER at some point)
-	Power on storage
o	Shelves
o	Bridges
-	Verify storage on bridges and switches
-	Enable ISLs"

Please can the procedure be updated to reflect this?

Reference: https://burtview.netapp.com/burts/1539230#Notes_wenzel_TueMar0708:56:54EST2023

**Comment by netapp-aoife** [comment]
Hello. Thanks for raising this. We'll review this feedback and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi @tgoreham  Thanks again for raising this. I'm closing this issue as the feedback is being tracked in this Jira ticket: https://jira.ngage.netapp.com/browse/ONTAPDOC-1471
