### ISSUE TITLE
Power on procedure step 6 is missing switches and disk shelves

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap-metrocluster#282]
Page: [Powering off an entire MetroCluster IP configuration](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_off_an_entire_mcc_ip_configuration.html)

5. Power off the following equipment at the site:

    Storage controllers

    MetroCluster IP switches

    Storage shelves

6. Wait for thirty minutes and then power on all the controllers.

The procedure step #6 above is missing the MetroCluster IP switches and Storage shelves.

Updated procedure 6:

6. Wait for thirty minutes and then power on all storage shelves, MetroCluster IP switches, and storage controllers.

**Comment by netapp-aoife** [comment]
Hello, thanks very much for raising this issue. We'll review this feedback and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hello, thanks again for raising this issue. The feedback has now been addressed in our documentation.
