### ISSUE TITLE
Switch name in Step 5 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#285]
Page: [Replace an IP switch or change the use of existing MetroCluster IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html)

In Step 5 we say: 

"If you are using new switches, power off the old switch, remove the cables, and physically remove the old IP_switch_B_1." 

Do we really need to give a specific switch name there? We haven't mentioned we're working on Switch B_1 until that point, but are referring to the "old switch". If we just leave is as the old switch that might avoid some confusion. 

Thanks,
Viktor

**Comment by netapp-aoife** [comment]
Thanks Viktor. We'll review this and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi Viktor, thanks again for raising this. We've made this update in the documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html
