### ISSUE TITLE
Missing supported platforms 

### ISSUE THREAD

**Issue by Kenneth-borg** [NetAppDocs/ontap-metrocluster#287]
Page: [Platform port assignments for NVIDIA supported SN2100 IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/port_usage_sn2100.html)

The following platforms are currently supported:

    FAS500f / AFF C250 / AFF A250

    FAS8300 / AFF C400 / AFF A400

    FAS8700

    FAS9000 / AFF A700

    AFF C800 / AFF A800

The following platforms and configurations are not currently supported:

    MetroCluster FC-to-IP Transition

    An eight-node MetroCluster configuration

"Switch port usage for AFF C400, AFF A400, AFF A700 or FAS9000, FAS8300 or FAS8700 AFF A800"
also missing the FAS9500 and A900

we are missing the A900 / FAS9500. on the same page we do list the systems port assignment.

**Comment by netapp-aoife** [comment]
Hi Kenneth, thank you for raising this issue. We will review and update the documentation accordingly.
