### ISSUE TITLE
Adding steps/warning for changing HM monitoring to use SNMPv3 with Brocade switches 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#288]
Page: [Upgrading or downgrading the firmware on a Brocade FC switch](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.html)

Hello everyone, 

As per Brocade release notes (examples taken for 9.1.1a - https://docs.broadcom.com/doc/FOS-911a-RN) SNMPv2 is deprecated/unsupported: 

9.2.4 SNMP Support

Fabric OS v9.1.x documents the supported MIBs in the Brocade Fabric OS MIB Reference Manual. For information about
SNMP support in Fabric OS software and how to use MIBs, refer to the Brocade Fabric OS Administration Guide for
Fabric OS v9.1.x.

NOTE Fabric OS v9.1.x support SNMPv1 and SNMPv3, SNMPv2 deprecated in Fabric OS v9.0.1a, SNMP
walk using SNMPv2 is blocked in Fabric OS v9.1.x

By default, adding switches to HM monitoring uses SNMPv2c and we might be risking customers ending with being unable to monitor their switches after a FabOS upgrade, if they don't also go through the process of changing the switch monitoring to use SNMPv3 (preferably before the FabOS upgrade). 

For example, here we have general steps on how to configure SNMPv3 on the Brocade switches and how to create an SNMP user for them in ONTAP: 

https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software

https://kb.netapp.com/onprem/ontap/metrocluster/How_to_set_the_authentication_protocol_and_privacy_protocol_passwords_for_the_snmpv3user_SNMPv3_user_on_a_Brocade_switch

Overall, to avoid any issues with HM and Brocade switches on 9.1.x (or possibly even earlier), we might have to add steps/warning that SNMPv2 monitoring might not work properly with the newer FabOS releases. 

Best regards, 
Viktor

**Comment by netapp-aoife** [comment]
Hi Viktor, thanks for raising this. We'll review this feedback and update the documentation accordingly.

**Comment by viktorpenev** [comment]
Hi Aoife,

I've already created a doc_burt for this one, so might be worth following on that one - 1555239.

Thanks,
Viktor

**Comment by netapp-aoife** [comment]
That's great, thanks Viktor!

**Comment by netapp-aoife** [comment]
Hi @viktorpenev , thank you again for raising this. I'm closing this issue because the update is being tracked in BURT 1555239.
