### ISSUE TITLE
MetroCluster configurations don't show the Cluster Interconnect ports used.

### ISSUE THREAD

**Issue by mikecabibbo** [NetAppDocs/ontap-metrocluster#290]
Page: [Platform port assignments for Cisco 3232C or Cisco 9336C switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/port_usage_3232c_9336c.html)

MetroCluster configurations don't show the Cluster Interconnect ports used.  There is no mention of e0a/e1a in that document on docs.netapp.com.  Cluster Interconnect is not mentioned anywhere on that document at all.  That document appears to only be showing MCC and shelf connections, but not CI.  It would be a good addition.

**Comment by netapp-aoife** [comment]
Hello, thanks for raising this issue. We'll review the feedback and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hello, thanks again for raising this issue. We have reviewed this feedback and determined that the documentation correctly directs to the Hardware Universe for cluster interconnect port usage information. Please let us know if you have any further feedback or questions.

Thank you,
Aoife
