### ISSUE TITLE
Add steps for SNMPv3 support for BES switches 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#292]
Page: [Configuring Broadcom IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html)

Hi everyone, 

At the moment I can't find steps for monitoring the BES switches in a MetroCluster environment via SNMPv3. We have burt https://burtview.netapp.com/burts/1358228, which was preventing us from using anything but SNMPv2c, but that is solved now and customer might want to start using SNMPv3 for security reasons. 

Steps here provide details on configuring SNMPv3 both on the switch and in ONTAP - https://kb.netapp.com/onprem/Switches/Broadcom/How_to_setup_SNMPv3_monitoring_on_a_BES-53248_cluster_switch

Removing the community-string from the switch running-config should disable access to the switch via SNMPv2c: 

#no snmp-server community 'cshm1!'

Best regards, 
Viktor

**Comment by netapp-aoife** [comment]
Hi Viktor, thanks for this valuable feedback. We'll let you know when the documentation has been updated.

**Comment by viktorpenev** [comment]
Hi Aoife,

Maybe the step for removing the community string is not needed, cause we might have some internal processes, which rely on that. But apart from that, we can probably add something like that.

Best regards,

Viktor Penev
Technical Support Escalation Engineer
Technical Support Center

***@***.******@***.***>

My normal working hours are Day-to-Day, 9 a.m. - 5.30 p.m. CET.

For technical assistance on a new or existing case, please call:
* US & Canada 888-4-NETAPP // * EMEA/Europe  00-800-44-638277 // * Asia/Pacific  800-8008-0800

You may also get Support on the Web at http://mysupport.netapp.com<http://mysupport.netapp.com/>.

Everyone in the NetApp Technical Support Center is committed to providing the highest level of customer satisfaction.
If you believe that the level of support can be improved, please contact my manager, Joaquin Moreno, at ***@***.******@***.***>.

[A close up of a logo  Description automatically generated]<https://www.netapp.com/us/index.aspx>


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

**Comment by viktorpenev** [comment]
Hi Aoife, I hope you're doing well. 

Can you please let me know what's the status of the ticket? We've been getting more requests on how to enable SNMPv3 for BES switches in MetroCluster IP systems. 

Thanks, 
Viktor

**Comment by netapp-aoife** [comment]
Hi @viktorpenev thanks for raising this issue. This has now been addressed in the documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_config_switch_health.html
