### ISSUE TITLE
IP Switch Request

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-metrocluster#293]
Page: [Where to find procedures for MetroCluster maintenance tasks](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html)

This table is very handy overview.  Could we get a section added to it for "IP switch" similar to the FC switch that exists there now?

**Comment by netapp-aoife** [comment]
Hi there, thanks again for raising this issue. The issue has now been addressed in the documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html

**Comment by TimMcGue** [comment]
Excellent - thank you!  Very convenient to have that detail together.
