### ISSUE TITLE
Adding steps to allow Ethernet switch log collection to work on MCCIP BES-53248 switches 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#295]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html

### Page title

Configuring Broadcom IP switches

### Summary

Hi all, 

At the moment we have the following steps to enable Ethernet switch log collection, which allows to collect switch logs via ONTAP CLI, instead of having to manually get 'show tech-support' from a BES-53248 switch - https://docs.netapp.com/us-en/ontap-systems-switches/switch-bes-53248/configure-log-collection.html

Those steps, however, are currently applicable only to cluster BES-53248 switches. 

In order for the Ethernet log collection to work we have to enable SCP on the BES switches, which is currently not done in MCCIP - neither via RCF, nor via commands in the docs. 

The steps here work even on an already configured switch - https://confluence.ngage.netapp.com/display/ONTAP/Jute+switch+log+collection+procedure+1 - regenerated the keys as per the doc, provided the password for the admin user (could be a different one), enabled the collection and triggered a new collection. 

In a few minutes the collection was reported as completed: 

Cluster_A::*> system switch ethernet log show

 Log Collection Enabled: true

 Index Switch                               Log Timestamp        Status
------ ------------------------------------ -------------------  -------------
     1 SwtichA_1                            5/25/2023 05:23:47   complete

The files are located at https://<node-mgmt-ip>/spi/<node-name>/etc/log/shm-cluster-log.tgz 

The steps for the generation of the keys kind of overlap with the "Reset the switch to defaults", but it might be best to add a new section after applying the RCFs and link to it - not everyone will be willing to enable SCP and switch logging, but if they want to they could jump to that section to avoid generating keys multiple times and doing a few switch reboots. 

Thanks, 
Viktor

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi Viktor, thanks for raising this issue. We'll let you know when this has been addressed in the documentation.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev I'm closing this issue as it is being tracked internally in ONTAPDOC-2392.
