### ISSUE TITLE
Behavior of unmirrored aggregates differ between FMC and MC-IP

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#298]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html

### Page title

Understanding MetroCluster data protection and disaster recovery

### Summary

Comment on section "How MetroCluster configurations use SyncMirror to provide data redundancy"
---
The behavior of unmirrored aggregates during switchover differs between FMC and MC-IP.
What is described here only applies to FMC. In MC-IP an unmirrored aggregate stays offline after a switchover (both negotiated and unplanned) But after a negotiated switchover one is able to manually force the unmirrored aggregate online if one so chooses.
If people read the documentation as is they will get a false impression of MC-IP behavior which could lead to unplanned outages.
The behavioral difference is briefly mentioned in section "Differences in switchover between MetroCluster FC and IP configurations" but that is way down the documentation and does not go into too much detail.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hello, thank you for this feedback. We'll review it and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
hi @nlsntap  This issue is now addressed here: https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#how-metrocluster-configurations-use-syncmirror-to-provide-data-redundancy

Thanks again for raising this and helping us improve the documentation.
