### ISSUE TITLE
Possible step 4 changes or note needed

### ISSUE THREAD

**Issue by JMnetapp** [NetAppDocs/ontap-metrocluster#300]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_removing_a_disaster_recovery_group.html

### Page title

Removing a Disaster Recovery group

### Summary

While working on technical case 2009588530, we were removing 4-nodes from the MCCIP config. Working through this document and also using the associated KB
https://kb.netapp.com/onprem/ontap/metrocluster/How_to_remove_a_DR-Group_from_a_MetroCluster#

In the Doc
https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_removing_a_disaster_recovery_group.html#removing-the-dr-group-nodes-from-each-cluster

After completing step 3, step 4 has you run a few commands to remove the connections, interfaces, and dr-group configs. Found that none of these commands would work and continued to fail stating that the DR-group does not exist. It seems that maybe in later versions of ONTAP these steps are not needed as the command in step 2b already removes/deletes the DR-group.

We were able to move forward after confirming with other config show commands that these had already completed. More details in the case.

Setup:
8-node MCCIP
4 A300 (nodes to be removed)
4 A400 (nodes that will stay in the config)
ONTAP 9.10.1P8

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-martyh** [comment]
Thank you for sharing this feedback -- we will review the procedure to see if we can remove the steps or make them conditional based on ONTAP version.

**Comment by netapp-aoife** [comment]
Hi @JMnetapp thanks again for raising this. Closing this issue as the feedback is being tracked internally in ONTAPDOC-1984.
