### ISSUE TITLE
Table should include 8n

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#301]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html

### Page title

Choosing your transition procedure

### Summary

The table at the bottom of the page for choosing the procedure should include 8 node.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Thanks, Michelle. We'll make this change and let you know when it has been published.

**Comment by netapp-aoife** [comment]
This issue has now been fixed in the documentation. Thanks again for brining this to our attention.
