### ISSUE TITLE
Changes in switchover behavior with Mediator since 9.13.1

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#303]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mediator.html

### Page title

Differences between ONTAP Mediator and MetroCluster Tiebreaker

### Summary

Starting 9.13.1 two parameters have been added that influence MAUSO.

1) automatic forced switchover
It is mentioned at a different location of the documentation, but should be mentioned here as well as SO will get triggered eventhough NVRAM is NOT in sync.

2) MAUSO on DR-group failure
In case it's an 8-node MCIP configurations, one can configure to have SO initiated if one HA pair goes down and does need to wait until *ALL* nodes fail.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @nlsntap, thank you for bringing this to our attention. I'll verify your suggestions and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @nlsntap, we've linked to the pages that contain the relevant information on automatic forced switchover and managing MAUSO in IP configurations which you can view using this link:
[How the ONTAP Mediator supports automatic unplanned switchover](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mediator.html#how-the-ontap-mediator-supports-automatic-unplanned-switchover)
Thanks again for helping us improve our customer documentation.

**Comment by nlsntap** [comment]
The page still lists this note:
"MAUSO is initiated only if nonvolatile cache mirroring (DR mirroring) and SyncMirror plex mirroring is in sync at the time of the failure. "
This is not correct. Starting 9.13.1 an option is introduced to alter this behavior to have MAUSO being ihnitiated even if NVlog is NOT in sync.

**Comment by nlsntap** [comment]
The same is mentioned further below
"Both SyncMirror mirroring and DR mirroring of each node’s nonvolatile cache is operating and the caches and mirrors are synchronized at the time of the failure."
Again - configurable starting 9.13.1.

**Comment by nlsntap** [comment]
Also still incorrect:
"If a site disaster occurs. A site disaster is a failure of all nodes at the same site."
Starting 9.13.1 one can configure if *all* nodes or both nodes of an HA pair will trigger a MAUSO.

**Comment by netapp-pcarriga** [comment]
Hi @nlsntap - Thank you for following up with the clarifications above and apologies for the confusion. I'll verify and update the documentation accordingly.

**Comment by nlsntap** [comment]
Need to re-open this incident once more as it is still incorrect/incomplete.
The page states:
"Both SyncMirror mirroring and DR mirroring of each node's nonvolatile cache is operating and the caches and mirrors are synchronized at the time of the failure."

A note has to be added that this behavior can be altered in the way that SO may occur even if NVRAM is NOT in sync. An option has been introduced with 9.13.1 to also force MAUSO if NVRAM is out-of-sync.

**Comment by nlsntap** [comment]
With that, the other note on this page is also not correct anymore:
"MAUSO is initiated only if nonvolatile cache mirroring (DR mirroring) and SyncMirror plex mirroring is in sync at the time of the failure. "

**Comment by netapp-pcarriga** [comment]
Hi @nlsntap, I'll consult with the MetroCluster team and update the documentation accordingly. Thank you!

**Comment by netapp-pcarriga** [comment]
Hi @nlsntap, we will be revising the MAUSO content in the ONTAP MetroCluster documentation and will incorporate your feedback during this process. I will update you here when this task is complete. Thanks for your patience and understanding.

**Comment by netapp-pcarriga** [comment]
Hi @nlsntap, I've opened an internal documentation task to track this request and added you as a watcher. I'm closing this issue and I'll follow up with you via the doc task. Thanks!
