### ISSUE TITLE
Incorrect ONTAP version cited

### ISSUE THREAD

**Issue by netappacook** [NetAppDocs/ontap-metrocluster#305]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html

### Page title

Expanding a MetroCluster IP configuration

### Summary

In the following notation, I believe the version 9.1.1 specified is incorrect.  I believe this should state 9.9.1. 

You can configure the MetroCluster IP interfaces from either cluster. Also, beginning with **ONTAP 9.1.1**, if you are using a layer 3 configuration, you must also specify the -gateway parameter to create MetroCluster IP interfaces. Refer to [Considerations for layer 3 wide-area networks](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @netappacook Thanks for bringing this to our attention. We'll verify and update the documentation accordingly.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: [Configuring intercluster LIFs, creating the MetroCluster interfaces, and mirroring root aggregates](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html#configuring-intercluster-lifs-creating-the-metrocluster-interfaces-and-mirroring-root-aggregates)
