### ISSUE TITLE
FAS500f ADP support

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#306]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_drive_assignment.html

### Page title

Considerations for automatic drive assignment and ADP systems in ONTAP 9.4 and later

### Summary

The FAS500f *does* support ADP. In fact that is the default configuration in line with A250 and C250. Looks like the marketing declaration of it being a "FAS" has thrown people off as any other FAS platform does nOT support ADP in MCIP configuration. The FAS50f essentially is and behaves like AFF, incl. ADP. It's just being named FAS.
Please correct.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @nlsntap thanks for raising this. We'll verify and let you know when the documentation is updated.
