### ISSUE TITLE
Can't install TieBreaker successful

### ISSUE THREAD

**Issue by shawhm** [NetAppDocs/ontap-metrocluster#308]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/task_install_the_tiebreaker_software.html

### Page title

Installing the Tiebreaker software

### Summary

it shows:
Error creating token: Post "https://127.0.0.1:8200/v1/auth/token/create": http: server gave HTTP response to HTTPS client

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @shawhm, thanks for bringing this to our attention. We'll verify the issue and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi @shawhm thanks again for raising this. The issue has now been addressed in the documentation.
