### ISSUE TITLE
Steps unclear in 3c 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#309]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_brocade_fc_switch_mcc.html

### Page title

Replacing a Brocade FC switch

### Summary

Can we add additional steps in 3c as it's not clear what "Configure the new switch as described in _MetroCluster Installation and Configuration, but skipping the “Configuring zoning on Brocade FC switches” procedure." exactly means. 

The link added leads to https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html, which is very generic - customers then have 2 options to configure the switches - with RCFs or manually. 

The doc page says that zoning is configured later, but there's doesn't seem to additional info on the topic. Can you please update that, too? 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev, thank you for raising this. We'll verify and let you know when the documentation has been updated.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev thanks again for raising this issue. The documentation has now been updated to address your feedback: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_brocade_fc_switch_mcc.html
