### ISSUE TITLE
Change to version info

### ISSUE THREAD

**Issue by csa72** [NetAppDocs/ontap-metrocluster#311]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/task_install_the_tiebreaker_software.html

### Page title

Installing the Tiebreaker software

### Summary

The following text:
Only MetroCluster Tiebreaker 1.4 is compatible with RHEL versions 7-7.9.
Should read:
Only MetroCluster Tiebreaker 1.4 is compatible with RHEL & CentOS versions 7-7.9.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @csa72 thanks for bringing this to our attention. We'll verify and update the documentation and let you know when the changes are complete.

**Comment by netapp-aoife** [comment]
Hi @csa72  thanks for raising this issue. This issue has now been addressed in the documentation.
