### ISSUE TITLE
Add row for no hardware failures

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#315]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html

### Page title

Choosing the correct recovery procedure

### Summary

Could we add a new row to the top of the table for: "No hardware failures"
This should point to the same procedure as non controller failure:
https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/task_recover_from_a_non_controller_failure_mcc_dr.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp  thanks for this suggestion. We'll update the documentation and let you know when the issue is addressed.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp thanks again for this suggestion. We have updated the documentation to address this feedback.
