### ISSUE TITLE
SNTP commands need updating

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#321]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html

### Page title

Configuring Broadcom IP switches

### Summary

The SNTP commands in step 11 are not applicable in versions of EFOS 3.10.x and higher.

Can we please update the documentation to reflect this?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
HI @tgoreham, thanks for highlighting this issue. I'll look into this and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @tgoreham, we've added the instruction to use the 'ntp' command beginning with EFOS 3.10.0.3 and later. 

Thanks again for highlighting this issue and helping us improve the customer documentation.
