### ISSUE TITLE
Example command is different in my opinion

### ISSUE THREAD

**Issue by mmoret73** [NetAppDocs/ontap-metrocluster#322]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html

### Page title

Configure the ONTAP Mediator service from a MetroCluster IP configuration

### Summary

metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster
[Job 439] Job succeeded: Modify is successful.

In advanced:
metrocluster modify -allow-automatic-forced-switchover true
Error: invalid argument "-allow-automatic-forced-switchover"

In Diag
netapp01::*> set -privilege diag

Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y

netapp01::*> metrocluster modify -allow-automatic-forced-switchover true
Error: invalid argument "-allow-automatic-forced-switchover"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @mmoret73 thanks for raising this issue. We'll verify and update the documentation accordingly.

**Comment by darkstar** [comment]
The parameter `-allow-automatic-forced-switchover true` is incorrect.  The correct parameter is `allow-auto-forced-switchover true`. The other parameter reported by the OP, `-auto-switchover-failure-domain` has nothing to do with this and is irrelevant

**Comment by netapp-aoife** [comment]
Hi @mmoret73  thanks again for raising this, and thanks @darkstar for providing additional information. This issue has now been addressed in the documentation.
