### ISSUE TITLE
AFF A150 missing in table of platform considerations for MCC compliant switches

### ISSUE THREAD

**Issue by netapp-martyh** [NetAppDocs/ontap-metrocluster#323]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html

### Page title

Considerations for using MetroCluster-compliant switches

### Summary

A150 in Open N/W configuration is not supported, so it should be in the table but show null entries "-".

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @netapp-martyh , this issue has now been addressed in the documentation.
