### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#324]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_monitoring_the_mcc_configuration.html

### Page title

Monitoring the MetroCluster configuration

### Summary

Hi all, 

There's a broken link: 

link:../install-ip/concept_mediator_requirements.html

Best regards, 
Viktor

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev thanks for bringing this to our attention. I'll let you know when the link has been fixed.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev  thanks again for raising this. The issue has now been addressed in the documentation.
