### ISSUE TITLE
ATTO bridge can be updated using different protocol/servers

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#326]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html

### Page title

Updating firmware on a FibreBridge bridge

### Summary

Hi all, 

We've run a few tests and figured out that ATTO bridges can be upgraded not only via HTTP as the document suggests now. I've tested that with FTP and that also works: 

Cluster_A::*> storage bridge run-cli -name ATTO_2000001086abe8c0 -c FlashImages
[Job 2246] Job is queued: Executing ATTO CLI command "FlashImages" on bridge "ATTO_2000001086abe8c0"..
;Type         Version
;=====================================================
   Primary    4.40 001C
 Secondary    4.30 001N

Ready.

[Job 2246] Job succeeded.

Cluster_A::*> storage bridge firmware update -bridge ATTO_2000001086abe8c0 -uri ftp://admin:netapp123@10.216.37.39/FB760440.zbd
[Job 2247] Job is queued: System bridge firmware update job.

Cluster_A::*>
Cluster_A::*>
Cluster_A::*> storage bridge run-cli -name ATTO_2000001086abe8c0 -c FlashImages
[Job 2248] Job is queued: Executing ATTO CLI command "FlashImages" on bridge "ATTO_2000001086abe8c0"..
;Type         Version
;=====================================================
   Primary    4.40 001C
 Secondary    4.40 001C

Ready.

[Job 2248] Job succeeded.

Separate tests have been done with sFTP, TFTP and they also seem to work. 

Can you please update the documentation and list the different options supported, so that customers won't have to setup an HTTP server, if they already have FTP working? 

Thanks,
Viktor

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev  Thanks for raising this and for providing detailed information. We'll verify this and let you know when the issue has been addressed.

**Comment by viktorpenev** [comment]
Hi @netapp-aoife, are there any updates on this one?

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: 
[Updating firmware on a FibreBridge bridge](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html)
