### ISSUE TITLE
Add a comment regarding the ONTAP version of the existing.

### ISSUE THREAD

**Issue by quang186** [NetAppDocs/ontap-metrocluster#328]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html

### Page title

Choosing your transition procedure

### Summary

I've faced a recent situation while colleagues are transitioning from A700 to A900 and FC to IP.
The existing nodes were running 9.12.1P3 while this version was not available to download anymore. So A900 has been upgraded to 9.12.1P5.
The difference in the P release version introduce failure in MCC commands when trying to create DR-group.

Even if it sounds logical, is this possible to highlight the fact that the existing and future added nodes need to run the same ONTAP version. Not only Feature release but also Service Update release?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @quang186 thank you for this suggestion. We'll verify and let you know when the documentation has been updated.

**Comment by netapp-aoife** [comment]
Hi @quang186  This issue has now been addressed in the documentation at the following link: https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html 

Thanks again for helping us improve the documentation.
