### ISSUE TITLE
Site landing page is missing a description

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap-metrocluster#329]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/index.html

### Page title

MetroCluster Documentation

### Summary

The index page should include a description between the site title and the tiles.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @netapp-bcammett  thank you for raising this. We'll let you know when the documentation has been updated.

**Comment by netapp-aoife** [comment]
Hi @netapp-bcammett, thanks again for pointing this out. We've updated the documentation to address this issue.
