### ISSUE TITLE
Option to create PDF shows single page by default and this is not useful

### ISSUE THREAD

**Issue by jenatnetapp** [NetAppDocs/ontap-metrocluster#33]
Page: [Deciding whether to use the MetroCluster IP Installation and Configuration Guide](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_deciding_whether_to_use_this_guide_mcc_ip_installation_and_configuration_guide.html)

**Comment by netapp-martyh** [comment]
PDF interface updates are coming. Will close this issue when they are published.

**Comment by netapp-martyh** [comment]
Updates have been made.
