### ISSUE TITLE
Entry systems supported for MCIP Tech Refresh?

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#331]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_tech_refresh_mcc.html

### Page title

Choosing a system refresh method

### Summary

Hi,
the table does not show any of the entry platforms being supported with this Tech Refresh procedure. Yet the RCFGenerator tool allows combinations including entry platforms which indicates QA has been performed and the combination is supported.
Please update the table and procedure to reflect support for entry platforms.
Thanks and regards, Niels

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @nlsntap thanks for raising this issue. We'll get this verified and will let you know when the documentations has been updated.

**Comment by netapp-aoife** [comment]
Hi @nlsntap, thanks again for raising this. I'm closing this issue because your feedback is being tracked in: https://jira.ngage.netapp.com/browse/ONTAPDOC-1369
