### ISSUE TITLE
Added steps required for setting up SNMPv3 on a Cisco switch.

### ISSUE THREAD

**Issue by csa72** [NetAppDocs/ontap-metrocluster#333]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-snmpv3-in-a-metrocluster-configuration

### Page title

Configuring the MetroCluster software in ONTAP

### Summary

The document includes the steps to set up SNMPv3 on a Brocade switch but not on a Cisco switch.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @csa72 thanks for raising this issue. We'll verify and let you know when the documentation is updated.

**Comment by netapp-aoife** [comment]
Hi @csa72 thanks again for raising this issue. This feedback is now addressed in the documentation. See step 5 here: https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-snmpv3-in-a-metrocluster-configuration
