### ISSUE TITLE
Add a link to HWU to find supported transceivers if changing ISL ports 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#339]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_add_remove_or_change_isl_ports_nondisruptively.html

### Page title

Adding, removing, or changing ISL ports nondisruptively

### Summary

Hello everyone, 

Can we add in the document a step on how customers can determine the supported transceivers they can use here - I suppose it should be just a link to HWU Switch section. 

Thanks,
Viktor

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev thanks for your suggestion. We'll let you know when the documentation is updated.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here:
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_add_remove_or_change_isl_ports_nondisruptively.html
