### ISSUE TITLE
Add steps for controller reboot after 'metrocluster configure' (similar to MCC-IP installation guide) 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#341]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html

### Page title

Expanding a MetroCluster IP configuration

### Summary

Hi all, 

Can you please review and update the steps in https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html#finalizing-the-addition-of-the-new-nodes to include reboot of all new nodes, similar to https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html#implementing-the-metrocluster-configuration (Step 4)? 

Thanks, 
Viktor

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by viktorpenev** [comment]
Hi Aoife, can you please provide an update on this? A PSC has just reported another issue with NVRAM mirroring not coming up during an expansion, which was resolved with nodes reboot.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev thanks again for raising this. The documentation has now been updated to reflect your feedback. See step 1(c) here: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html#finalizing-the-addition-of-the-new-nodes
