### ISSUE TITLE
Add a more specific link for Step 3c 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#342]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_brocade_fc_switch_mcc.html

### Page title

Replacing a Brocade FC switch

### Summary

Hi all, 

Can you please add a link, which points to the specific steps for configuring a MetroCluster FC Brocade switch as right now it points to https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html, which is very generic. 

Recently we had an issue with a switch replacement where customer thought we don't have proper documentation for configuring the settings, port speed, ISL distance. 

Thanks,
Viktor

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev , thanks for this suggestion. I'll let you know when this is updated.

**Comment by netapp-aoife** [comment]
Hi @viktorpenev, thanks for raising this.  The documentation has now been updated to address this issue. We've updated the link and added a new step to verify the zoning config (6b) : https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_brocade_fc_switch_mcc.html
