### ISSUE TITLE
Addcumulus 5.x commands to the configuration

### ISSUE THREAD

**Issue by koekies125** [NetAppDocs/ontap-metrocluster#349]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_nvidia.html

### Page title

Configure the NVIDIA IP SN2100 switch

### Summary

Greetings,

I would be good to have next to cumulus 4.x commands also cumulus 5.x commands for the configuration for these switches. Just like the page below.
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-cumulus-mode-sn2100-cluster.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @koekies125, thanks very much for this feedback. We'll review and let you know when this issue is addressed.
