### ISSUE TITLE
Typo - Being instead of Begin

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-metrocluster#35]
From: Goreham, Tom <Tom.Goreham@netapp.com> 
Sent: Monday, May 3, 2021 2:27 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_configure_mediator.html

Hello,

The first steps says “Before you being” instead of “Before you begin”.

Many Thanks,

Tom Goreham
Technical Support Engineer
MetroCluster

NetApp
00800 44638277 (EMEA/Europe)
tom.goreham@netapp.com

**Comment by netapp-martyh** [comment]
This issue has been fixed. Thank you for the feedback!
