### ISSUE TITLE
Page title does not match the title in the sidebar

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap-metrocluster#352]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes.html

### Page title

MetroCluster

### Summary

If you select "Release notes" in the sidebar this page loads and its simply titled "MetroCluster" which seems odd.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @netapp-bcammett thanks again for letting us know about this issue. The issue is fixed here: https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes.html
