### ISSUE TITLE
C-Series controllers missing

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#355]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html#platform-specific-network-speeds-and-switch-port-modes-for-metrocluster-compliant-switches

### Page title

Considerations for using MetroCluster-compliant switches

### Summary

Wondering if the C-Series variants of AFF and ASA are missing in the table or if they indeed not supported.
Please clarify and add accordingly.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @nlsntap thanks very much for raising this. We'll let you know when your feedback is addressed in the documentation.

**Comment by netapp-aoife** [comment]
Hi @nlsntap I'm closing this issue as it is already being tracked. I have sent you an email update with the details. Thanks!
