### ISSUE TITLE
Missing link - Where to find additional information

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-metrocluster#36]
From: Bachman, Phil <Phil.Bachman@netapp.com> 
Sent: Wednesday, April 28, 2021 4:39 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/reference_where_to_find_additional_information_mcc_service_guide.html#metrocluster-and-miscellaneous-guides

Greetings,

There appears to be a missing hyperlink in this table.

 
![Where to find additional information](https://user-images.githubusercontent.com/66023260/116921821-2c097a80-ac72-11eb-83d9-e6947cec1fb3.png)

-- Phil

Philip Bachman
Solution Architect

**Comment by netapp-martyh** [comment]
Hi Phil - The link has been fixed. Thanks for the feedback!
