### ISSUE TITLE
ASA controllers missing from table

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#360]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_drive_assignment.html

### Page title

Considerations for automatic drive assignment and ADP systems in ONTAP 9.4 and later

### Summary

Hi,

This page has a great table with all different controllers and the minimum recommended and required drive for each.
BUT... I am missing the ASA controllers. Assume it's the same limits as for AFF but assumptions can be wrong.

Please can you consider adding ASA to the tables?

Thanks in advance,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
hi @estarz thanks again for raising this issue. Your feedback has now been addressed in the documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_drive_assignment.html
