### ISSUE TITLE
SSE Feedback - Factory Defaults Order of Operations

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-metrocluster#361]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html

### Page title

Upgrade RCF files on MetroCluster IP switches

### Summary

This step:

2 - Prepare the IP switches for the application of the new RCF files.

And this step:

3 - Download and install the IP RCF file, depending on your switch vendor.

Need to be done one switch at a time.  However, this warning isn't shown until step #3.  

Update the switches in the following order: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2

Just by reading it is possible to misinterpret and perform step #2 on all switches and then do step #3 one switch at a time which would result in issues.  

I'm not sure the best way to convey this detail.  But basically you do this order:
Switch_A_1 Step #2 and #3

Switch_B_1 Step #2 and #3

Switch_A_2 Step #2 and #3

Switch_B_2 Step #2 and #3

This section has a similar type back and forth at the bottom that might be good to mimic:
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_firmware_on_mcc_ip_switches.html

Thanks as always for the great documentation!!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @TimMcGue  thanks you for this feedback and for providing detailed information. We'll review this and will let you know when the documentation is updated.

**Comment by netapp-aoife** [comment]
Hi @TimMcGue  thanks again for raising this issue. Your feedback has now been addressed in the documentation. We have added a bullet to the "About this task" section to clarify that all steps in the procedure should be performed in the order: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html#verify-that-the-rcf-file-is-supported

**Comment by TimMcGue** [comment]
Looks perfect - thank you!
