### ISSUE TITLE
Change the wording to ensure the HA-config is always verified

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#363]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_verify_haconfig.html

### Page title

Verifying the ha-config state of components

### Summary

We should change this sentence: 
"For systems received from the factory, this value is preconfigured and you do not need to verify it."

To something like:
"For systems received from the factory, this value is preconfigured but should still be verified as an incorrect setting could lead to an inappropriate root volume size being provisioned."

While the setting should indeed be correct coming from the factory, it's always better to check it because trying to fix this later can be much more difficult.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp thanks for raising this. We'll review and update the documentation accordingly.
