### ISSUE TITLE
Clarity needed on whether having Mediator or Tiebreaker is required.

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#365]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mediator.html

### Page title

Differences between ONTAP Mediator and MetroCluster Tiebreaker

### Summary

The doc page here can be interpreted as requiring the use of either Tiebreaker or Mediator, when it is really a choice between Tiebreaker, Mediator or neither. Could we do something to make this clearer?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp thanks for this feedback! We'll review and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @michelef-netapp, we've provided the following information to clarify that you can choose Tiebreaker, ONTAP Mediator, or neither:
_It is not required to use the MAUSO or Tiebreaker software; however, if you choose to not use either of these services, you must perform a manual recovery if a disaster occurs._

Thanks again for helping us improve the customer documentation.
