### ISSUE TITLE
Language clean up

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#368]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#illustration-of-the-local-ha-pairs-in-a-metrocluster-configuration

### Page title

Parts of a MetroCluster IP configuration

### Summary

There are a few terms used in this doc that don't follow our regularly used conventions.

In section "Illustration of the MetroCluster IP and cluster interconnect network"
1. "Each node in the MetroCluster IP configuration has specialized LIFs for connection to the back-end IP network"
Can we change "specialized LIFs" to "specialized interfaces". We generally don't refer to the MetroCluster interfaces as LIFs.

2. The second bullet point "One intercluster LIF". Since this is referring to connections to the backend IP network, this should be "Two Cluster Interfaces". This may need further rework as there are platforms where the MetroCluster interfaces and Cluster interfaces are shared.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp thank you for bringing this to our attention. We'll review this and will let you know when it has been addressed in the documentation.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp thanks again for raising this issue! We've now updated the documentation to reflect your feedback here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#illustration-of-the-metrocluster-ip-and-cluster-interconnect-network
