### ISSUE TITLE
Feedback on search engine

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-metrocluster#37]
From: Penev, Viktor <Viktor.Penev@netapp.com> 
Sent: Friday, April 30, 2021 4:14 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_prepare_for_the_mcc_installation.html#hardware-setup-checklist

Hello team, 

This feedback is not specifically for the doc itself, but more about the search engine. When searching for “compliant switches” for MetroCluster IP, it’s a bit difficult to find the exact info you need. 

The information is in a section, part of “Preparing for the MetroCluster installation”. Even when I use the whole title in the search box, it doesn’t seem to be returning the specific doc where I can find the details: 
![About the search engine](https://user-images.githubusercontent.com/66023260/116922881-90790980-ac73-11eb-8253-fcd6d8ae5916.png)

 

Please let me know if this is not the right way to submit this – I can do it via Github if necessary.

Thanks, 

Best regards, 

Viktor Penev
Technical Support Engineer
Technical Support Center

**Comment by netapp-martyh** [comment]
Hi Viktor - We have addressed this issue -- if it recurs, please open another issue and we will take a look.

Thanks,
Marty
