### ISSUE TITLE
Remove ATTO 6500N

### ISSUE THREAD

**Issue by michelef-netapp** [NetAppDocs/ontap-metrocluster#370]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fb_new_install.html

### Page title

Installing FC-to-SAS bridges and SAS disk shelves

### Summary

The ATTO 6500N is no longer supported. Can we remove the section "Cabling a FibreBridge 6500N bridge with disk shelves using IOM6 or IOM3 modules" and all 6500N references?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @michelef-netapp thanks for noticing this. We'll review and let you know when the documentation is updated.

**Comment by netapp-pcarriga** [comment]
Hi @michelef-netapp, I've created an JIRA task to track this doc request internally, and added you as a watcher. Thanks!
