### ISSUE TITLE
Unnecessary Steps

### ISSUE THREAD

**Issue by ReneMeier** [NetAppDocs/ontap-metrocluster#374]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html

### Page title

Expanding a MetroCluster IP configuration

### Summary

The last two steps are are not necessary in the Expanding a MetroCluster IP configuration. Only if you want to remove the old nodes (transition)

- Move the MDV_CRS volumes from the old nodes to the new nodes in advanced privilege.
- Move epsilon from an old node to a new node:

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @ReneMeier thank you for raising this issue. We'll review your feedback and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi there, thanks again for raising this issue. We've made some updates to the topic here to address your feedback: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html#finalizing-the-addition-of-the-new-nodes
