### ISSUE TITLE
Latest Platforms Not Updated in the Switch Settings

### ISSUE THREAD

**Issue by jaintap** [NetAppDocs/ontap-metrocluster#376]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html

### Page title

Considerations for using MetroCluster-compliant switches

### Summary

Platform-specific network speeds and switch port modes for MetroCluster-compliant switches
The above table in the page have lot of missing MCCIP Supported Platform , please update this after referring to the h/w page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @jaintap thanks very much for raising this issue. We'll let you know when the documentation has been updated.

**Comment by netapp-aoife** [comment]
Hi @jaintap thanks again for this feedback. This issue is now addressed in the documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-network-speeds-and-switchport-modes.html
