### ISSUE TITLE
Section "Controller models limited to four-node configurations" not accurate

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#377]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.html

### Page title

Required MetroCluster IP components and naming conventions

### Summary

The section "Controller models limited to four-node configurations" is not accurate anymore as of 9.13.1 where all of the listzed models are supported in a) an 8-node configuration as well as b) two seperate 4-node MCCs sharing switches.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @nlsntap thanks for raising this. We'll let you know when this feedback is addressed in the documentation.

**Comment by netapp-aoife** [comment]
Hi @nlsntap thanks again for bringing this to our attention. This issue is now addressed in the documentation and a wider review of the page is being tracked internally in ONTAPDOC-1744.
