### ISSUE TITLE
Typo in table cell

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#378]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html

### Page title

Expanding a MetroCluster IP configuration

### Summary

In the table of section "Supported platform combinations when adding a second DR group" there is a typo in the column listing AFF/ASA A/C800. The ASA A800 is listed twice, the ASA C800 is missing.
This applies to the cell of "8node DRgroup 1".

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @nlsntap thanks for raising this issue. We'll verify and let you know when this has been addressed.

**Comment by netapp-aoife** [comment]
Hi @nlsntap thanks again for raising this issue. I've captured this feedback in ONTAPDOC-1734 for internal tracking.
