### ISSUE TITLE
ECDSA Key

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-metrocluster#381]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html

### Page title

Configuring Broadcom IP switches

### Summary

For the cluster switch similar configuration we have this:
https://docs.netapp.com/us-en/ontap-systems-switches/switch-bes-53248/configure-ssh.html

In step 2 we have this:
crypto key generate ecdsa 521

In this document we have step 9c as this:
If you are using the FIPS compliant version of EFOS, generate the ECDSA keys. The following example creates the keys with a length of 256. Valid values are 256, 384 or 521.

(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 256

Should we have both documents be the same as always generating the ecdsa 521 key regardless of EFOS version?  That helps with log collection in ONTAP.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for the feedback. We will investigate and follow up here.

**Comment by netapp-aoife** [comment]
Hi @TimMcGue, thanks again for raising this issue! We've now updated the example to reflect your feedback here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults
