### ISSUE TITLE
Tidy up section "Finalizing the addition of the new nodes"

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#386]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html

### Page title

Expanding a MetroCluster IP configuration

### Summary

Hi,

A while ago I created issues #267 and #276, both for something I experienced performing FC to IP transition.

Today I performed a "normal" 4->8 node IP expansion and realise that some of the changes from #267 and #276 applies here as well.
Like which node to run the command from. Change from "one of the new nodes" to "any of the nodes in any of the clusters"
And the table that was added for guide if you only have one data aggregate.

Feel it would make sense to include the changes to the 4->8 IP docs as well. Might be they apply to 4->8 FC as well but not sure.

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @estarz thanks for this feedback and the extra information you've provided. We'll verify and let you know when the documentation is updated!

**Comment by netapp-aoife** [comment]
Hi @estarz thanks again for raising this issue. Your feedback is now addressed here: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_expand_a_four_node_mcc_ip_configuration.html#finalizing-the-addition-of-the-new-nodes
