### ISSUE TITLE
Feedback on 'How the Tiebreaker software detects site failures'

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-metrocluster#39]
From: Ferguson, Michelle <Michele.Ferguson@netapp.com> 
Sent: Wednesday, May 12, 2021 8:23 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_monitoring_the_mcc_configuration.html#how-the-tiebreaker-software-detects-site-failures

•  IP network (present in MetroCluster IP configurations)
This type of network is composed of two redundant IP switch networks. Each network has two IP switches, with one switch of each switch fabric co-located with a cluster. Each cluster has two IP switches, one from each switch fabric. All of the nodes have connectivity to each of the co-located FC switches. Data is replicated from cluster to cluster over the ISL.

This should be IP switches not FC.

Regards, 
Michelle Ferguson

Michelle Ferguson
Sr. Escalation Engineer
Technical Support Center, part of NetApp Customer Support Delivery

NetApp
00-800-44-638-277
michelle.ferguson@netapp.com

**Comment by netapp-martyh** [comment]
Hi Michelle - This issue has been fixed.

Thanks,
Marty
