### ISSUE TITLE
Cable matrix are pictures and hard to read and should be table

### ISSUE THREAD

**Issue by pdavy** [NetAppDocs/ontap-metrocluster#396]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/port_usage_9336c_shared.html

### Page title

Platform port assignments for a Cisco 9336C-FX2 shared switch

### Summary

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/port_usage_9336c_shared.html#cabling-an-aff-a320-aff-c400-asa-c400-aff-a400-asa-a400-aff-a700-aff-c800-asa-c800-aff-a800-aff-a900-or-asa-a900-system-to-a-cisco-9336c-fx2-shared-switch

shows a table. Its an image.  Zoom in / out is not usable to make it readable or to copy it to a spreadsheet as a reference.   

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @pdavy thanks for your feedback on the documentation! We are aware of this issue and are working to improve it. We'll let you know when we have an update.

**Comment by netapp-aoife** [comment]
Hi @pdavy thanks again for this feedback. We've addressed the readability issues with the image here and plan to make future improvements : https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/port_usage_9336c_shared.html#tables_not_connecting_ns224
