### ISSUE TITLE
Feedback on :Updating firmware on FibreBridge 7500N on configurations running ONTAP 9.3.x and earlier or 6500N bridges"

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-metrocluster#40]
From: Penev, Viktor <Viktor.Penev@netapp.com> 
Sent: Thursday, May 13, 2021 6:27 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html#updating-firmware-on-fibrebridge-7500n-on-configurations-running-ontap-9-3-x-and-earlier-or-6500n-bridges

Hello team, 

On Step 8: 

job show -name Storage bridge firmware update

The syntax is incorrect as it returns: 

mcc8040-ams1::*> job show -name Storage bridge firmware update

Error: "bridge" is an invalid value for field "-id <integer>"

However, if we run: 

mcc8040-ams1::*> job show -name "Storage bridge firmware update job name" <<<<<<<<<<<<<<<<< name is taken from ‘job show’. 
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
7574   Storage bridge firmware update job name mcc8040-ams1 mcc8040-ams1-02 Running
       Description: Storage bridge firmware update job

Best regards, 

Viktor Penev
Technical Support Engineer
Technical Support Center

NetApp
viktorp@netapp.com

**Comment by netapp-martyh** [comment]
Hi Viktor - The command has been updated. Please let us know if you see any further issues.

Thanks,
Marty
