### ISSUE TITLE
Metrocluster IP is not supported FAS platforms(case#2010061674)

### ISSUE THREAD

**Issue by jiron1973** [NetAppDocs/ontap-metrocluster#401]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_drive_assignment.html

### Page title

Considerations for automatic drive assignment and ADP systems in ONTAP 9.4 and later

### Summary

I am case#2010061674 support engineer.

Could you please add consideration column in below?

・MetroCluster IP supports ADP (Advanced Drive Partitioning) in AFF platforms. ADP is not supported on FAS platforms.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @jiron1973 thanks for this suggestion. We'll verify and let you know when the documentation is updated.

**Comment by netapp-aoife** [comment]
Hi @jiron1973 thanks again for raising this issue. This feedback is now addressed here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_drive_assignment.html
