### ISSUE TITLE
Auto-Revert option correct?

### ISSUE THREAD

**Issue by netappmf** [NetAppDocs/ontap-metrocluster#404]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html

### Page title

Replace an IP switch or change the use of existing MetroCluster IP switches

### Summary

Hello Everyone

in step 3. of the guide auto-revert of the cluster Lifs is disabled
then in step 9. the new switched should be powered up and in step 11 the auto-revert is enabled.

However if we enable auto-revert after powering up the switches, the lifs will never switch back to their original ports. So in my opinion Auto-revert should be enable before step 9. or there has to be a manual step after step 11 to revert the cluster lifs back to their home port.

Best Regards
Marco

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi Marco, thanks for raising this issue. We'll verify and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi @netappmf, thank you again for bringing this to our attention. This issue is being tracked internally in ONTAPDOC-2222. Please reach out to doccomments@netapp.com if you need more information.
