### ISSUE TITLE
[MetroCluster] Table is missing entries for the new models (A70, A90, A1k)

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/ontap-metrocluster#408]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-network-speeds-and-switchport-modes.html

### Page title

Platform-specific network speeds and switch port modes for MetroCluster-compliant switches

### Summary

The [doc page](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-network-speeds-and-switchport-modes.html) is missing values for the newly-released models, the A70, A90 and A1k.

If those models support MetroCluster Compliant Switches, they should be listed with the correct switch mode.

If they don't (yet?) support MetroCluster Compliant Switches, they should be listed (like the other models that don't support ist) with dashes in the table

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @darkstar thanks for raising this issue. We'll review and send you an update soon.

**Comment by netapp-aoife** [comment]
Hi @darkstar thanks again for raising this issue. The documentation has been updated here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-network-speeds-and-switchport-modes.html
