### ISSUE TITLE
Missing setup links for six (6) supported platforms under item #3

### ISSUE THREAD

**Issue by pgbachman** [NetAppDocs/ontap-metrocluster#41]
Page: [Racking the hardware components](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_rack_hw_components.html)

Missing links for multiple platforms:
- A250  https://library.netapp.com/ecm/ecm_download_file/ECMLP2870798
- A400  https://library.netapp.com/ecm/ecm_download_file/ECMLP2858854
- A700  https://library.netapp.com/ecm/ecm_download_file/ECMLP2874463
- FAS 500f  https://library.netapp.com/ecm/ecm_download_file/ECMLP2872833
- FAS 8300 & 8700  https://library.netapp.com/ecm/ecm_download_file/ECMLP2858856
- FAS9000  https://library.netapp.com/ecm/ecm_download_file/ECMLP2874463

**Comment by netapp-martyh** [comment]
Links have been added. when the platform content is migrated to GH we will just point generically to the AFF-FAS repo.
