### ISSUE TITLE
page lacks mentioning Broadcom switch

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#411]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-considerations-layer-2-layer-3.html

### Page title

Considerations when deploying MetroCluster in shared layer 2 or layer 3 networks

### Summary

At the top of the page only Cisco switches are mentioned to support shared L2/L3 configurations, but this is also supported with Broadcom switch, which is correctly reflected later on that page. Should be added to the top to avoid confusion about what is or is not supported.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @nlsntap thanks for bringing this to our attention. We'll review and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi @nlsntap thanks again for raising this! The documentation is updated to address your feedback here: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-considerations-layer-2-layer-3.html
