### ISSUE TITLE
Create seperate procedures for switch replacement of the same type and for new switch type in MCIP configuration

### ISSUE THREAD

**Issue by btom82** [NetAppDocs/ontap-metrocluster#412]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html

### Page title

Replace an IP switch or change the use of existing MetroCluster IP switches

### Summary

I would suggest to separate the procedures for replacing switches of the same type from the procedure to replace switches with a new type. Now are both procedures mixed together. I found it very confusing and I am not the only one. I got the same remarks from our partners.
I had to do it recently going from a BES-53248 to Cisco Nexus 9336C switch and I used my own procedure like this :

High level steps
1.	Disable Auto-revert of the Cluster LIFs on both clusters. Check the iscsi backend connections.
2.	Disconnect the Cables and power off the switch Switch A_1
3.	Rack and boot the new Nexus A_1 switch
4.	Disable the MetroCluster ISL ports on the new Nexus A_1 switch
5.	Cable the new Nexus A_1 Switch (except Intra ISL cable)
6.	Drive to Site B. Disconnect the Cables and power off the switch of Switch B_1
7.	Rack and boot the new Nexus B_1 switch
8.	Cable the new Nexus B_1 Switch (except Intra ISL cables)
9.	Re-enable the MetroCluster ISL ports on the new Nexus A_1 switch.
10.	Check the health on both clusters. Check the iscsi backend connections.
11.	Disconnect the Cables and power off the switch of Switch B_2. Cluster Interconnect becomes active on new Nexus B_1 Switch.
12.	Rack and boot the new Nexus B_2 switch. Cable the IntraCluster ISL cables between the 2 Nexus Switches on site B.
13.	Disable the MetroCluster ISL ports on the new Nexus B_2 switch.
14.	Cable the new Nexus B_2 Switch. Check the health on both clusters + iscsi backend connections.
15.	Drive back to site A. Disconnect the Cables and power off the switch of Switch A_2. Cluster Interconnect becomes active on new Nexus A_1 Switch.
16.	Rack and boot the new Nexus A_2 switch. Cable the IntraCluster ISL cables between the 2 Nexus Switches on site A.
17.	Cable the new Nexus A_2 Switch.
18.	Re-enable the MetroCluster ISL ports on the new Nexus B_2 switch.
19.	Re-enable Auto-revert of the Cluster LIFs on both clusters.
20.	Revert all Cluster InterConnect LIFs back to their homeport. Check the health on both clusters

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @btom82 thanks for this feedback. We'll verify and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi @btom82 thanks again for providing this feedback. This issue is now being tracked internally in ONTAPDOC-2222.
