### ISSUE TITLE
The storage failover modify command needs update to hwassist-partner-ip and hwassist-partner-port attributes

### ISSUE THREAD

**Issue by kaminis85** [NetAppDocs/ontap-metrocluster#413]
### Page URL

https://docs.netapp.com/us-en/ontap-cli//storage-failover-modify.html

### Page title

storage failover modify

### Summary

The storage failover modify command needs update to hwassist-partner-ip and hwassist-partner-port attributes.

Attaching screenshot for detailed info about that.
<img width="653" alt="Screenshot 2024-07-18 at 6 09 24 PM" src="https://github.com/user-attachments/assets/dc609da3-25ac-4eb3-99b4-5fad39317776">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @kaminis85 thanks for raising this issue. We'll verify and update the documentation accordingly.

**Comment by netapp-martyh** [comment]
Hi Kamini, are you requesting a fix to https://docs.netapp.com/us-en/ontap-cli//storage-failover-modify.html#parameters based on your screenshot, or an update to the MetroCluster docs?

Thanks,
Marty

**Comment by kaminis85** [comment]
Hello @netapp-martyh 
I am requesting a fix to https://docs.netapp.com/us-en/ontap-cli//storage-failover-modify.html#parameters 
I was not able to open the GitHub issue on that page, so I had to open this request/issue via this MetroCluster page

**Comment by netapp-martyh** [comment]
Thanks @kaminis85, I redirected this to doccomments via email.
