### ISSUE TITLE
firmware update

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-metrocluster#418]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_sle_fc_to_sas_bridge.html

### Page title

Replacing a single FC-to-SAS bridge

### Summary

In the section:

Hot-swapping a bridge with a replacement bridge of the same model

Step 16 is:
Update the FibreBridge firmware on each bridge.

If the new bridge is the same type as the partner bridge upgrade to the same firmware as the partner bridge. If the new bridge is a different type to the partner bridge, upgrade to the latest firmware supported by the bridge and version of ONTAP. See the section "Updating firmware on a FibreBridge bridge" in MetroCluster Maintenance.

That is this document:
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html

The issue is that pushes update through the fiber connections to the bridge.  However, at that point in the bridge replacement we have not connected the FC and SAS ports so we are unable to update that way.

For the 7600n bridge we had to enable IP ports here:
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_enable_ip_port_access_on_the_fibrebridge_7600n_bridge_guides.html

And then update the firmware directly on the bridge itself.  

This might need some engineering review if the scenario is better to update firmware using out of band IP access or to connect to the MetroCluster with whatever bridge firmware came with it and the update through ONTAP. 

Thanks as always for your great work with documentation!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @TimMcGue thanks for raising this issue. We'll verify and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi @TimMcGue thanks for raising this issue. The documentation has now been updated to address your feedback: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-bridge-with-a-replacement-bridge-of-the-same-model
