### ISSUE TITLE
Broken link to "Upgrade, revert, or downgrade"

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/ontap-metrocluster#42]
Page: [Where to find procedures for MetroCluster maintenance tasks](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html)

"Upgrade, revert, or downgrade"

regards
Siegfried

**Comment by netapp-martyh** [comment]
Hi Siegfried - This link has been resolved.

Thanks,
Marty
