### ISSUE TITLE
Controller HBA and FCVI connections missing for MetroCluster 1 DR group 1 using both ATTO FC connections

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#422]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html

### Page title

Port assignments for FC switches when using ONTAP 9.1 or later

### Summary

Hi,

As the title says. The table for "Configurations using FibreBridge 7500N or 7600N using both FC ports (FC1 and FC2)", "MetroCluster 1 or DR Group 1" is missing rows for controller HBA and FCVI.

All rows are for the ATTO bridges, "Stack N".

It might be that the very first table on that page, that only contains controllers 1 and 2, should have the title changed - currently it has "using one FC port (FC1 or FC2) only" but the same ports would apply when using both FC ports.
If it said using one OR two FC ports, that would also solve the issue.

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @estarz thanks for providing this feedback. We'll verify and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi @estarz thanks again for this feedback. Closing this issue as the update is being tracked internally in ONTAPDOC-2386.
