### ISSUE TITLE
Do we ever enable the new switches

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#423]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_to_new_brocade_switches.html

### Page title

Upgrading to new Brocade FC switches

### Summary

Will perform a 6505 to G720 migration for a customer and thought I'd check the documented procedure before I start my own.
So in principle, my own plan was OK. Disable old and new switches in Fabric 1, move cables to new switches, enable new switches and check connectivity.
Repeat on fabric 2.

But reading the docs, it just wants me to switchcfgpersistentdisable but never enable again?
Or is it on applying the RCF, where we reset the switch to defaults, that it gets enabled? But then why explicitly disable the new switches...

In this particular case we have staged the new switches and already configured them a few weeks ago.
So we will just disable them before moving cables.

Feel the docs might need a little bit of clarification.

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @estarz thanks very much for this feedback. We'll investigate the issue and update the documentation accordingly.

**Comment by netapp-aoife** [comment]
Hi, thanks again for this feedback. We've made some updates to address this issue here: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_to_new_brocade_switches.html
