### ISSUE TITLE
SNMP config commands do not work

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#427]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html

### Page title

Configuring the Brocade FC switches manually

### Summary

On a newly configured G720, snmpconfig --set snmpv1 fails. Reason is that snmp has no config at all and --set tries to modify an existing config. So you need to run snmpconfig --add snmpv1 <+ more options>.

If this is fixed and while you are on it, you might want to document how to configure SNMPv3 as well.

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @estarz thanks for letting us know. We'll verify and send you an update when the documentation is updated.

**Comment by netapp-aoife** [comment]
Hi @estarz thanks again for raising this. Closing this issue as your feedback is now bring tracked internally in ONTAPDOC-2573.
