### ISSUE TITLE
switchcfgpersistentdisable does NOT disable both switches in a fabric

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#428]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_to_new_brocade_switches.html

### Page title

Upgrading to new Brocade FC switches

### Summary

Performed this operation together with a customer yesterday.
We had both read through the docs and had doubt about this:
<img width="514" alt="Screenshot 2024-09-06 at 17 46 34" src="https://github.com/user-attachments/assets/0cfb5cb7-f779-4fa1-8252-fd3c3ff12ec9">

None of us recognized that portcfgpersistentdisable would disable both switches in a fabric.
Like what if the fabric was 10 switches (not MCC of course) would then all 10 be disabled.
That would be a truly scary command.

In any way, just as we thought, we remembered correctly and the command actually had to be run on both switches.

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @estarz thanks for raising this. We'll clarify and update the documentation accordingly.
