### ISSUE TITLE
snmpconfig --set command does not work on newly installed G720

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-metrocluster#430]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html

### Page title

Configuring the MetroCluster software in ONTAP

### Summary

In the section describing how to setup SNMPv3 it says to run this command on the switch:
snmpconfig --set snmpv3

This failed for me and a customer as no SNMP config was present.
We needed to add one with "snmpconfig --add snmpv3" and a few additional flags.
Once we had the config, we could run the --set command and change values as per this document.

Would be great if the docs could be updated with command that do work on a new switch.

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @estarz thanks for helping us improve the documentation. We'll verify and update accordingly.

**Comment by netapp-aoife** [comment]
Hi @estarz thanks again for this feedback. Closing this as it is being tracked internally in ONTAPDOC-2573.
