### ISSUE TITLE
Add SFTP and HTTP

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap-metrocluster#434]
### Page URL

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.html

### Page title

Upgrading or downgrading the firmware on a Brocade FC switch

### Summary

Since 9.0 (lowest version still in support) Brocade added SFTP and HTTP to the firmwaredownload command:

https://techdocs.broadcom.com/us/en/fibre-channel-networking/fabric-os/fabric-os-commands/9-0-x/Fabric-OS-Commands-Chapter/firmwareDownload.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @TimMcGue thanks for bringing this to our attention. We'll verify and update the documentation accordingly.
