### ISSUE TITLE
Generated PDF documentation unusable

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/ontap-metrocluster#44]
The generated PDF is totally unusable. It contains hundreds of pages looking like this:
![image](https://user-images.githubusercontent.com/43795/119518857-34d50400-bd79-11eb-90e5-69010e0fbb82.png)
or this:
![image](https://user-images.githubusercontent.com/43795/119519229-8b424280-bd79-11eb-93f4-d4de90b3f6c3.png)

In the past there was at least a usable PDF in the regular ONTAP documentation ZIP, but that has been removed and been replaced by this, it seems.

Please, either bring back the old documentation or fix the MCC IP generated PDFs so that we can actually print it out and use it when standing in our customers' datacenter...

Page: [Preparing for the MetroCluster installation](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_prepare_for_the_mcc_installation.html)

**Comment by netapp-martyh** [comment]
The PDF issues have been resolved - if you find additional issues, please let us know.

Thanks,
Marty
