### ISSUE TITLE
MCC FC does not support partitioned disks

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/ontap-metrocluster#45]
Page: [Preparing for the upgrade](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_prepare_for_the_upgrade_add_2nd_controller_to_create_ha_pair.html)

... disks with available **partitions** that you can ...

Metrocluster FC does not support partitioned disks, so please remove partitions in the doc.

regards
Siegfried

**Comment by netapp-martyh** [comment]
Text has been updated.
