### ISSUE TITLE
Save the environment: saveenv``bye

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/ontap-metrocluster#46]
Page: [Clearing the configuration on a controller module](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_clear_the_configuration_on_a_controller_module_mcc.html)

I think step 3 is incorrect:
Save the environment: saveenv``bye

**Comment by netapp-martyh** [comment]
Hi Siegfried -

I believe **saveenv** is correct but **bye** is not needed. I will make updates.

Thanks,
Marty

**Comment by netapp-martyh** [comment]
Resolved.
