### ISSUE TITLE
DOcument is missing a step

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/ontap-metrocluster#47]
Page: [Preparing cluster ports on an existing controller module](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_prepare_cluster_ports_on_the_exist_controller.html)

The document is explaining in detail what to do if a data LIF is owned by a port that is needed for the IP space, but it is missing the step/command to add the port the the Cluster broadcast domain:
 broadcast-domain add-ports -ipspace Cluster -broadcast-domain Cluster -ports cluster1-01:e0a

regards
Siegfried

**Comment by netapp-martyh** [comment]
Resolved.
