### ISSUE TITLE
Doc page link for Layer 3 concept is broken

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#48]
Page: [Considerations for MetroCluster IP configurations](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mcip.html)

In the "Characteristics of MetroCluster IP interfaces" section there is a link for Layer 3 concept - https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_layer_3.html - which is broken.

**Comment by netapp-martyh** [comment]
Hi Viktor - this has been fixe.d
