### ISSUE TITLE
Adding a link to Brocade RCF download page

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#49]
Page: [Downloading the Brocade FC switch RCF file](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_download_the_brocade_fc_rcf_switch_software.html)

Can we add a link to the Brocade RCF download page as currently it doesn't seem so easy for one to find the files needed. I think this might be the right link - https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab - but it's worth to double check it. 

Thanks,
Viktor

**Comment by netapp-martyh** [comment]
Hi Viktor - the link to the page has been added. That is the correct link.
