### ISSUE TITLE
Feedback on "Sending a custom AutoSupport message after maintenance" documentation

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-metrocluster#52]
From: Von Bredow, Patrick <Patrick.VonBredow@netapp.com> 
Sent: Monday, June 7, 2021 5:36 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Cc: Agopovic, Eva <Eva.Agopovic@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html#sending-a-custom-autosupport-message-after-maintenance

Hello Team,

Is this command actually available pre 9.8? 
metrocluster switchover -controller-replacement true

In my lab systems I can’t find it on 9.7. 

In the guide it says it’s possible for 9.3 2n-MCC 

•  You can use this procedures with certain ONTAP versions:
•	Two-node configurations are supported in ONTAP 9.3 and later.
•	Four and eight node configurations are supported in ONTAP 9.8 and later.
Do not use this procedure on four- or eight-node configurations running ONTAP versions prior to 9.8.

Patrick von Bredow 

Technical Support Escalation Engineer (MetroCluster)
Technical Support Center

Patrick.vonBredow@netapp.com

**Comment by ntap-bmegan** [comment]
@netapp-martyh or @netapp-folivia - Please update status or close if work is complete.

**Comment by netapp-folivia** [comment]
Hi,

This issue will be finalized soon. The command 'metrocluster switchover -controller-replacement true' only became available with ONTAP 9.8. We are currently seeking an alterative step(s) for configurations using earlier versions of ONTAP.

Thanks,
Olivia

**Comment by netapp-folivia** [comment]
Hi,

I have added back the old command for 2-node configurations running earlier versions of ONTAP. This update will be published in the next few days.

Thanks,
Olivia

**Comment by netapp-martyh** [comment]
Moving to internal repo at Patrick's request.
