### ISSUE TITLE
modify configure refresh command to add -allow-with-one-aggregate true

### ISSUE THREAD

**Issue by glenn-tourangeau** [NetAppDocs/ontap-metrocluster#53]
Page: [Refreshing the MetroCluster configuration with new controllers](https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_the_mcc_configuration_mcc_configure_refresh.html)

In Step 1 the configure refresh command needs the option -allow-with-one-aggregate true added to the command

Reason is the configure refresh tries to create the MDV volume on a mirrored data aggregate on the new nodes. The mirrored aggregate cannot be created until the metrocluster configuration is completed but you cannot refresh the configuration until the data aggregate is created.

The option -allow-with-one-aggregate true crates the MDV volume on the existing data aggregate after which the MDV volume will need to be moved to the new mirrored aggregate after it is created.

Steps we used to workaround the problem in attached file.
[configure_refresh_steps.txt](https://github.com/NetAppDocs/ontap-metrocluster/files/6643843/configure_refresh_steps.txt)

**Comment by netapp-martyh** [comment]
Update has been made.
