### ISSUE TITLE
storage disk show -fields owner,dr-home incorrect in ONTAP 9.8 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#54]
Page: [Confirming that the DR partners have come online](https://docs.netapp.com/us-en/ontap-metrocluster/manage/task_confirm_that_dr_partners_have_come_online.html)

Just had a remote session with a customer who was following the doc page and noticed that he doesn't see the 'dr-home' field populated for his system. ONTAP version is 9.8P2. Output (truncated): 

CL-AGOS-SN::> storage disk show -fields owner,dr-home
disk    owner         dr-home
------- ------------- -------

Info: This cluster has partitioned disks. To get a complete list of spare disk capacity use "storage aggregate
      show-spare-disks".
1.10.0  CL-AGOS-BT-02 -
1.10.1  CL-AGOS-BT-02 -
1.10.2  CL-AGOS-BT-02 -
1.10.3  CL-AGOS-BT-02 -
1.10.4  CL-AGOS-BT-02 -
1.10.5  CL-AGOS-BT-02 -
1.10.6  CL-AGOS-BT-02 -

The owner listed here - CL-AGOS-BT-02 - is actually the original disk owner (which in ONTAP 9.7 would appear as 'dr-home'), e.g.: 

ClusterA::> storage disk show -fields owner, dr-home
disk    owner       dr-home
------- ----------- -----------
1.12.0  ClusterA-02 ClusterB-02
1.12.1  ClusterA-02 ClusterB-02
1.12.4  ClusterA-02 ClusterB-02
1.12.5  ClusterA-02 ClusterB-02
1.12.6  ClusterA-02 ClusterB-02
1.12.7  ClusterA-02 ClusterB-02

Can we add a note for that in the doc page as it could cause some confusion?

**Comment by netapp-folivia** [comment]
Hi Viktor, we've revised this page and made a few changes, see them here: https://docs.netapp.com/us-en/ontap-metrocluster/manage/task_verify_SVMs%20are_running_and_aggregates_are_online.html
