### ISSUE TITLE
Missing platform from MetroCluster page

### ISSUE THREAD

**Issue by pgbachman** [NetAppDocs/ontap-metrocluster#57]
Page: [Required MetroCluster IP components and naming conventions](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.html)

The FAS2750 is missing from the list of platforms limited to a 4-node MetroCluster. Please add the FAS2750.

**Comment by netapp-martyh** [comment]
Update made.
