### ISSUE TITLE
MCC INstall guide - FC-to-SAS Bridge config - Commands should be separated and '' removed

### ISSUE THREAD

**Issue by patrick-netapp** [NetAppDocs/ontap-metrocluster#59]
Page: [Installing FC-to-SAS bridges and SAS disk shelves](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fb_new_install.html)

The commands to configure the ethernet port are all in one line / not very readable. 
Further, there are " ''  "  in between "mp1 disabled" and "set ethernetspeed", which I think the ATTO Bridge can't use. 
Here in bold. 
You can contact me on Teams if you have questions 

If using the CLI, you must run the following commands:set ipaddress mp1 ip-addressset ipsubnetmask mp1 subnet-maskset ipgateway mp1 x.x.x.xset ipdhcp mp1 disabled**``**set ethernetspeed mp1 1000

**Comment by netapp-martyh** [comment]
It looks like this is resolved. Patrick, please reopen if necessary.
