### ISSUE TITLE
Adding steps for offlining unmirrored aggregates

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#60]
Page: [Powering off and powering on a data center](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_on_and_power_off_a_data_center.html)

In Step 6 there might have to be steps for offlining unmirrored aggregates, as they are currently missing. If a customer tries to offline a plex from an unmirrored aggregate, they'll get the following error: 

mcc8040-ams2::> storage aggregate plex offline -aggregate viktor_unmirroed -plex plex0

Error: command failed: Failed to offline aggregate plex "viktor_unmirroed/plex0". Reason: This operation is not supported on unmirrored aggregates.

However, if the whole aggregate is offlined, it works fine. 

mcc8040-ams2::> storage aggregate offline -aggregate viktor_unmirroed

Aggregate offline successful on aggregate: viktor_unmirroed

Additionally, it might be a good idea to offline all LUNs or volumes they have in the aggregate before that.

**Comment by netapp-folivia** [comment]
Hi Viktor,

We've updated this section to include a step to move unmirrored aggregates (and LUNs and volumes located on unmirrored aggregates) offline (https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_on_and_power_off_a_data_center.html#powering-off-a-metrocluster-site).

Thanks!
Olivia
