### ISSUE TITLE
A400 ports - e3a,e3b

### ISSUE THREAD

**Issue by simonhazell** [NetAppDocs/ontap-metrocluster#63]
Page: [Configuring the clusters into a MetroCluster configuration](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html)

Are the "MetroCluster IP ports" for the A400 correct in this document? HWU shows the IWARP card (X1146A) being in slot 1, so ports 1a and 1b
![image](https://user-images.githubusercontent.com/86777481/124109858-80a55800-da5f-11eb-91aa-d4686ddd27dc.png)

**Comment by netapp-martyh** [comment]
Thanks, Simon. You are correct -- we will update the table to show e1a and e1b.

**Comment by netapp-martyh** [comment]
Resolved in hotfix 2021.11.21.
