### ISSUE TITLE
MetroCluster-compliant switches replacement

### ISSUE THREAD

**Issue by ArnaudAlbertini** [NetAppDocs/ontap-metrocluster#64]
Page: [Replacing an IP switch](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html)

Hello,
We received some feedback related to the replacement of MetroCluster-compliant switches in a MCC-IP configuration. The current page doesn't mention even the word MetroCluster-compliant. 

The only guideline is :
"This procedure is for Cisco or Broadcom switches. If you want to change the switch vendor, further steps are required."

Thanks,
Arnaud

**Comment by netapp-martyh** [comment]
Thanks, Arnaud. I will pursue this issue with the MetroCluster team.

**Comment by netapp-folivia** [comment]
Thanks for your feedback. I've clarified the wording and you should see this reflected on our pages soon.
