### ISSUE TITLE
Add steps for offlining all plexes

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#65]
Page: [Replacing a shelf nondisruptively in a fabric-attached MetroCluster configuration](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_a_shelf_nondisruptively_in_a_mcc_fc_configuration.html)

In Step 1 the documentation says: 

Offline the affected plexes on the controller where they are hosted 

However, if the plexes are offlined only for the affected shelf in the stack, and the procedure is followed, then we might end up with a node panic due to multiple disks missing as the we are disabling access to the whole stack, not just the affected shelf. 

E.g., we have 5 shelves in the stack from 0-5. Shelf 1 is the affected one, which has to be replaced. In that case we have to offline all the below as those plexes contain disks from those 5 shelves: 

aggrA1_0 >>> plex 0
dataA1_data >>> plex 0
 
aggrA2_0 >>> plex 0
dataA2_data >>> plex 0

aggrB1_0 >>> plex 1 
aggrB1_data >>> plex 1 

aggrB2_0 >>> plex 1
aggrB2_data >>> plex 1

That way we can ensure no disk panics will occur, while data is still read/written to the plexes on the "good" side.

**Comment by netapp-martyh** [comment]
Hi Viktor - 

Should we direct the user to offline all plexes with drives residing on shelves in the affected shelf stack:

1. Offline all plexes with disks on the affected shelf stack:
storage aggregate plex offline -aggr aggregate-name -plex plex-name

For example:
cluster_A_1::> storage aggregate plex offline -aggr aggrA_1_0 -plex plex0
cluster_A_1::> storage aggregate plex offline -aggr dataA_1_data -plex plex0
cluster_A_2::> storage aggregate plex offline -aggr aggrA_2_0 -plex plex0
cluster_A_2::> storage aggregate plex offline -aggr dataA_2_data -plex plex0
cluster_B_1::> storage aggregate plex offline -aggr aggrB_1_0 -plex plex1
cluster_B_1::> storage aggregate plex offline -aggr dataB_1_data -plex plex1
cluster_B_2::> storage aggregate plex offline -aggr aggrB_2_0 -plex plex1
cluster_B_2::> storage aggregate plex offline -aggr dataB_2_data -plex plex1

**Comment by viktorpenev** [comment]
Hi Martin,

Yes, that’s exactly the idea. All plexes, which have disks from that stack, have to be offlined – from both clusters.

Best regards,

Viktor Penev
Technical Support Engineer
Technical Support Center

NetApp
***@***.******@***.***>

[A close up of a logo  Description automatically generated]<https://www.netapp.com/us/index.aspx>


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

**Comment by netapp-martyh** [comment]
Resolved in hotfix, 2021.11.21.
