### ISSUE TITLE
Where to find additional steps to replace, for example, a CISCO switch by a Broadcom switch ?

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-metrocluster#67]
Page: [Replacing an IP switch](https://docs.netapp.com/
From: Ferrero, Fabrice <Fabrice.Ferrero@netapp.com> 
Sent: Tuesday, July 20, 2021 10:37 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html

                Hello Team,

Where can I find the additional steps when I need to replace, for example, a CISCO switch by a Broadcom switch ?

 

We also have question from Account Team regarding how it is possible to migrate from dedicated switches to Open Network mode and the opposite. I can't find any procedure in the documentation.

@+         Fab

________________________________________
Fabrice Ferrero
EMEA Field Support Engineer
us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html)

**Comment by ntap-bmegan** [comment]
@netapp-folivia - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @netapp-chandaj - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-ehoffman

**Comment by netapp-folivia** [comment]
Hi Megan,

We are waiting for a new procedure to be tested before we can publish.
Please keep this issue open.

Thanks,
Olivia

**Comment by ntap-bmegan** [comment]
@netapp-folivia - Any update?

**Comment by netapp-folivia** [comment]
Hi Fabrice,

I am closing this issue as we are tracking this update via the BURT (1491884).

Thanks,
Olivia
