### ISSUE TITLE
Edit command formatting on Step 4 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#69]
Page: [Performing a switchback](https://docs.netapp.com/us-en/ontap-metrocluster/manage/task_perform_a_switchback.html)

Can you please modify the 'metrocluster switchback' command to be more visible as currently it blends with the other text? Also maybe we can add 'metrocluster switchback -simulate' in the steps as well as an additional check.

**Comment by netapp-martyh** [comment]
In hotfix 2021.11.21.
