### ISSUE TITLE
Why "firmwaredownload" instead of "firmwaredownload -s"

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/ontap-metrocluster#72]
Page: [Upgrading or downgrading the firmware on a Brocade FC switch](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.html)

I wonder why the documentation suggest to use "firmwaredownload" instead of "firmwaredownload -s". I could understand if we are really performing an online update of the switch, but we are taking the switch offline "switchCfgPersistentDisable" so performing an online update while the switch is offline des not make sense.

I'm using the "firmwaredownload -s" for multiple years now and it has the advantage that I can skip brocade released. In addition it is also double as fast as "firmwaredownload" without the "-s".

regards
Siegfried Hepp - Netapp

**Comment by netapp-martyh** [comment]
Spoke with Tom, he says:
We are deliberately taking the switch offline, then update the FOS and then take it online again. This is the safest way doing it and this is what is qualified.

If people are using other steps and/or commands – they are not supported.

Thanks,
_T
