### ISSUE TITLE
Wrong initiator examples in zoning tables

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#76]
Page: [Configuring the Brocade FC switches manually](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html)

In the section "Zoning for FibreBridge 7500N bridges using both FC ports" there are zoning examples. The ones for the top fabric (e.g, 0a and 0c) are correct, but if you look at, e.g. MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 and MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2 it's showing again the same initiators 0b although for the second group that should be 0d. 

![image](https://user-images.githubusercontent.com/84146725/130349371-54263268-74cc-4393-9884-248700299f59.png)

Switch ports look okay, but the "Connects to..." field seems to be showing the same initiators. 

Same applies for all other examples where the initiators should be 0d.

**Comment by netapp-martyh** [comment]
Resolved in hotfix 2021.11.21.
