### ISSUE TITLE
Missing information re: ONTAP Mediator in the Monitoring documentation

### ISSUE THREAD

**Issue by pgbachman** [NetAppDocs/ontap-metrocluster#78]
Page: [Monitoring the MetroCluster configuration](https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_monitoring_the_mcc_configuration.html)

The page has a section entitled "Detecting failures with NetApp MetroCluster Tiebreaker software", which largely applies to the fiber channel version (aka MCC-FC or MC-FC).

Missing is a section on the differences between using the Tiebreaker and the ONTAP Mediator. This should include when to use which monitoring tool.

Also missing is a link to monitoring using the ONTAP Mediator. https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html

**Comment by netapp-martyh** [comment]
Issue is resolved.
