### ISSUE TITLE
AFF A400 and FAS8300 - X1146A Ports, are ... wrong?

### ISSUE THREAD

**Issue by chjones45** [NetAppDocs/ontap-metrocluster#79]
Page: [Required MetroCluster IP components and naming conventions](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.html)

The ports listed for the AFF A400 and FAS8300 are listed as e0b, e1b. The ports used for the MetroCluster IP Interfaces via the iWARP card are e1a, e1b. HWU also shows e1a and e1b as the MCC-IP Interface ports.

Can this be updated please.

**Comment by netapp-martyh** [comment]
Issue is resolved.
