### ISSUE TITLE
Clicking “See all results…” leads to a 404 Error

### ISSUE THREAD

**Issue by netapp-satyajit** [NetAppDocs/ontap-metrocluster#81]
Dear Doc Comments,

On the new Github documentation site it is very difficult to search as when I click “See all results…” I get a 404 Error:
docs_feedback: https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html

I’ve confirmed I get this issue with both the latest Safari and Chrome browsers.

Best Regards

Steve Ryles
Solutions Architect

**Comment by ntap-bmegan** [comment]
This is a known issue with search in repos with subfolders. A workaround has been posted via discussions.

**Comment by netapp-martyh** [comment]
This issue has been resolved.
