### ISSUE TITLE
Add additional general network requirements 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#82]
Page: [Considerations for using MetroCluster-compliant switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html)

Can we add in the "General requirements" a point, which says that 4 fabric switches are still required (having at least 2 switches per fabric), even though this is an open network setup? 

We have a customer, who is trying to setup a configuration with just 2 switches and claims that's as per documentation as it's not explicitly stated that it's not.

**Comment by netapp-martyh** [comment]
In hotfix, 2021.11.21.
