### ISSUE TITLE
Confusing documentation: Powering off a MetroCluster site

### ISSUE THREAD

**Issue by ta-osan** [NetAppDocs/ontap-metrocluster#83]
Page: [Powering off and powering on a data center](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_on_and_power_off_a_data_center.html)

Hi,

`Depending on your configuration and ONTAP version, identify and move offline affected plexes that are located at the disaster site`

What does 'disaster site' mean in context of the documentation?

`“Home” refers to the “home” owner, not the “current” owner.`

There is no reference to 'home' on this page other than in the quote above

`storage aggregate plex show -fields aggregate,status,is-online,Plex,pool`

Details an example of an output which shows aggregates from both DR groups, running the same command in my config (ONTAP 9.8) only shows the aggregates from the local DR group. 

`The affected plexes are those that are remote to cluster A.`

There is no indication in the documentation which cluster is being powered off, is it cluster A or cluster B? I assume cluster A, however it is only an assumption

Where are the commands run from, the cluster which is being powered off or the cluster which is remaining powered on?

No mention of treatment of local root aggregates/plexes - for the cluster being powered off I assume the local root plexes remain online? What about the remote root agg plex?

It would be good to include links for the points in the following section:

```
Equipment to be powered off

In a MetroCluster IP configuration, power off…​ 

MetroCluster IP switches
Storage controllers
Storage shelves

```

No step to power on storage controllers

**Comment by netapp-folivia** [comment]
Thank you for your feedback. This section has been revised: https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_power_on_and_power_off_a_data_center.html#powering-off-a-metrocluster-site
