### ISSUE TITLE
All links are broken in the "Preparing the MetroCluster IP controllers" doc page

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap-metrocluster#84]
Page: [Preparing the MetroCluster IP controllers](https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_prepare_ip_controllers_4n_transition.html)

Hello, 

All links in Step 3 seem to lead to "404 Page not found": 

![image](https://user-images.githubusercontent.com/84146725/132648308-c0c75b5f-8fb6-4824-9d74-f36988a864c8.png)

Can you please check and edit them? 

Thanks!

**Comment by netapp-martyh** [comment]
Fixed.
