### ISSUE TITLE
Only one SNMP trap host is currently supported

### ISSUE THREAD

**Issue by tgoreham** [NetAppDocs/ontap-metrocluster#86]
Page: [Configuring SNMP settings for Tiebreaker software](https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/task_configure_snmp_setts_for_tiebreaker_software.html)

Only one SNMP Trap host is currently supported and this needs to be declared in the documentation for clarity.

**Comment by netapp-folivia** [comment]
Hi! We will clarify the documentation to say only one SNMP trap host is supported. This will be reflected in our pages very soon. Thanks!
