### ISSUE TITLE
Need to add serial console access warning for config reset steps

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap-metrocluster#88]
Page: [Configuring Cisco IP switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_cisco.html)

Hi.. need to add this kind of info (borrowed from BES-53248 switch page) for this Cisco page - need physical/serial port access when resetting the config.

**About this task**
You must repeat these steps on each of the IP switches in the MetroCluster IP configuration.
You must be connected to the switch using the serial console.
This task resets the configuration of the management network.

**Comment by netapp-martyh** [comment]
In hotfix 2021.11.21.
