### ISSUE TITLE
with Fabric OS 8.2.0 and later there is no `ad` command anymore

### ISSUE THREAD

**Issue by danielpauldd** [NetAppDocs/ontap-metrocluster#91]
Page: [Configuring the Brocade FC switches manually](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html)

Some remarks to the section: "Setting the Brocade FC switch values to factory defaults"
With FOS release 8.2.0 and later there is no command `ad` anymore. Administrative Domains become deprected with 8.1.0

> Admin Domains are not supported in Fabric OS v8.1.0 and later. When this command is executed, it displays the following warning message: "Warning: 
> Admin Domains are not supported in Fabric OS v8.1.0. Admin Domain commands and functionality will be 
> removed in future Fabric OS versions."

**Comment by ntap-bmegan** [comment]
@netapp-folivia - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @danielpauldd - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-ehoffman

**Comment by netapp-folivia** [comment]
Hi Megan,

I'm waiting on review/approval for these steps. I will follow up today.
Please keep this issue open.

Thanks,
Olivia

**Comment by netapp-folivia** [comment]
Hi Chanda,

Yes, I spoke to a team member last week who said they will advise me regarding this update soon.

Thanks,
Olivia

**Comment by netapp-aoife** [comment]
Hi there, thank you again for raising this issue. Your feedback has now been addressed in the documentation here: https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html
