### ISSUE TITLE
no licensePort, licenseShow commands in Fabric OS 9.0.0 and later

### ISSUE THREAD

**Issue by danielpauldd** [NetAppDocs/ontap-metrocluster#92]
Page: [Configuring the Brocade FC switches manually](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html)

With Fabric OS 9.0.0 and later these commands are deprecated:
- `licenseAdd`
- `licenseIdShow`
- `licensePort`
- `licenseRemove`
- `licenseShow`

The commands are replaces with the command `license`

These implies the followig changes:

**Section "Reviewing Brocade license requirements":**
Step1: `license --show` instead of `licenseshow`
*The output is the same.*

**Section "Configuring basic switch settings":**
*AFAIK there is no static POD method in Fabric OS 9.0.0 and later.*

Step 4a:  `license --show -port` instead of `licensePort --show`
*The output is the same.*

**Comment by ntap-bmegan** [comment]
@netapp-folivia - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @danielpauldd - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-ehoffman

**Comment by netapp-folivia** [comment]
Hi Megan,

We are waiting for final approval for new steps. I will follow up on this today. Please keep this issue open.

Thanks,
Olivia

**Comment by netapp-folivia** [comment]
Hi Chanda,

The relevant team hopes to review the updates very soon. However, I'll send another reminder.

Thanks!
Olivia

**Comment by netapp-aoife** [comment]
Hi there, thank you for raising this issue. Your feedback has now been addressed in our documentation.
