### ISSUE TITLE
Maintain The MetroCluster Components leads to 404

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap-metrocluster#93]
Page: [Configuring the FC switches](https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/task_fcsw_configure_the_fc_switches_choice_topic.html)

Trying to access the section "Maintain The MetroCluster Components", which leads to a 404 message.

Kind regards, Niels

**Comment by netapp-martyh** [comment]
Resolved.
