### ISSUE TITLE
Remove steps for adding a FibreBridge from instructions for EXISTING pair of FibreBridges

### ISSUE THREAD

**Issue by csyoub** [NetAppDocs/ontap-metrocluster#98]
Page: [Hot-adding a stack of SAS disk shelves to an existing pair of FibreBridge 7500N bridges](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_hot_add_a_stack_to_exist_7500n_pair.html)

Remove steps for adding a FibreBridge from instructions for EXISTING pair of FibreBridges

Remove step 10.

**Comment by netapp-martyh** [comment]
In hotfix 2021.11.21.
