### ISSUE TITLE
disk_fw_update can cause outage of existing out of date disks

### ISSUE THREAD

**Issue by csyoub** [NetAppDocs/ontap-metrocluster#99]
Page: [Hot-adding a stack of SAS disk shelves to an existing pair of FibreBridge 7500N bridges](https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_hot_add_a_stack_to_exist_7500n_pair.html)

There are "loose" instructions about updating the firmware bundle AND instructions to disruptively take all out-of-date disks offline and update them.  You can't do both at once.

Either:
 - leave the firmware bundle in place AND do a disruptive update on ONLY the new disks OR
 - update the firmware bundle and ENSURE the existing disks are updated 24-48h in advance, then proceed with the disruptive update on ONLY the new disks

**Comment by netapp-folivia** [comment]
Hi, thanks for your feedback. We've clarified the documentation and you'll see the updated content on our pages soon.
